const catalogFieldFix = [
  {
    displayName: "分级",
    fieldName: "pathName",
    formType: "related_catalog",
    export: true,
    isSearch:true,
    show: true,
    orderId: -1,
    isSystem: 1,
    isDiy:true,
    tableName:"catalog",
  },
  {
    displayName: "产品视频",
    fieldName: "productVideo",
    formType: "attchment",
    export: false,
    show: true,
    orderId: -0.9,
    isSystem: 1,
    tableName:"catalog",
  },
  {
    displayName: "产品图片",
    fieldName: "productPic",
    formType: "attchment",
    export: false,
    show: true,
    orderId: -0.8,
    isSystem: 1,
    tableName:"catalog",
  },
  {
    displayName: "缩略图",
    fieldName: "thumbnail",
    formType: "attchment",
    export: false,
    show: true,
    orderId: -0.7,
    isSystem: 1,
    tableName:"catalog",
  },
  {
    displayName: "产品数量",
    fieldName: "productNum",
    formType: "text",
    export: true,
    show: true,
    isSystem: 1,
    tableName:"catalog",
  },
  {
    displayName: "创建人",
    fieldName: "createUserName",
    export: true,
    show: true,
    isSystem: 1,
    tableName:"catalog",
  },
  {
    displayName: "创建时间",
    fieldName: "createTime",
    export: true,
    show: true,
    isSystem: 1,
    tableName:"catalog",
  },
]

const catalogFieldFixForProduct = [
  {
    displayName: "产品视频",
    fieldName: "productVideo",
    formType: "attchment",
    export: false,
    show: true,
    orderId: -0.9,
    isSystem: 1,
    tableName:"catalog",
  },
  {
    displayName: "产品图片",
    fieldName: "productPic",
    formType: "attchment",
    export: false,
    show: true,
    orderId: -0.8,
    isSystem: 1,
    tableName:"catalog",
  },
  {
    displayName: "产品数量",
    fieldName: "productNum",
    formType: "text",
    export: true,
    show: true,
    isSystem: 1,
    tableName:"catalog",
  }
]

const productFieldFix = [
  // {
  //   displayName: "产品类型",
  //   fieldName: "catalogId",
  //   formType: "related_catalog",
  //   export: 1,
  //   isSystem: 1,
  //   tableName:"product",
  // },
  {
    displayName: "最近更新",
    fieldName: "updateTime",
    formType: "date",
    export: false,
    isSystem: 1,
    tableName:"product",
  },
  {
    displayName: "产品模板",
    fieldName: "productTemplate",
    formType: "text",
    export: false,
    isSystem: 0,
    tableName:"product",
  },
  {
    displayName: "服务团队",
    fieldName: "tags",
    export: true,
    isSystem: 0,
    exportAlias: "customerTags",
    tableName:"product",
  },
  {
    displayName: "提醒数量",
    fieldName: "remindCount",
    export: false,
    isSystem: 0,
    tableName:"product",
  },
  {
    displayName: "创建时间",
    fieldName: "createTime",
    export: true,
    isSystem: 0,
    tableName:"product",
  },
]

export {
  catalogFieldFix,
  productFieldFix,
  catalogFieldFixForProduct
}