const taskSteps = [
  {
    name: '新建',
    value: 'create',
    icon: 'xinjian',
    state: ['created', 'taskPool', 'refused'],
    flow: { state: true, overTime: 0, approvers: [] },
  },
  {
    name: '指派',
    value: 'allot',
    icon: 'zhipai',
    state: 'allocated',
    flow: { state: true, overTime: 0, approvers: [], leader: 'none' },
  },
  {
    name: '接受',
    value: 'accept',
    icon: 'jieshou',
    state: 'accepted',
    flow: { state: true, overTime: 0, approvers: [] },
  },
  {
    name: '开始',
    value: 'start',
    icon: 'kaishi',
    state: 'processing',
    flow: { state: true, overTime: 0, approvers: [], leader: 'none' },
  },
  {
    name: '完成',
    value: 'finish',
    icon: 'wancheng',
    state: ['finished', 'costed', 'closed'],
    flow: { state: true, overTime: 0, approvers: [], leader: 'none' },
  },
];

const taskFields = [
  {
    id: '43ee8e24-592b-11eb-9baf-00163e0d174e',
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'task',
    isSystem: 1,
    fieldName: 'taskNo',
    displayName: '工单编号',
    formType: 'taskNo',
    isNull: 0,
    isSearch: 1,
    isAdd: 1,
    placeHolder: '工单编号将在创建后由系统生成',
    setting: {},
    orderId: 0,
    templateId: '2e90e499-d982-46f8-b746-e1a8ab14282c',
    templateName: '新用户引导',
    defaultValue: null,
    enabled: 1,
    guideProfessions: [],
    isGuideData: false,
    isAppShow: 0,
    guideData: false,
  },
  {
    id: '43ef7f17-592b-11eb-9baf-00163e0d174e',
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'task',
    isSystem: 1,
    fieldName: 'customer',
    displayName: '客户',
    formType: 'customer',
    isNull: 0,
    isSearch: 1,
    isAdd: 1,
    placeHolder: '请选择客户或新建客户',
    setting: {
      customerOption: { product: true, address: true, linkman: true },
    },
    orderId: 1,
    templateId: '2e90e499-d982-46f8-b746-e1a8ab14282c',
    templateName: '新用户引导',
    defaultValue: null,
    enabled: 1,
    guideProfessions: [],
    isGuideData: false,
    isAppShow: 0,
    guideData: false,
  },
  {
    id: '43f066db-592b-11eb-9baf-00163e0d174e',
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'task',
    isSystem: 1,
    fieldName: 'level',
    displayName: '优先级',
    formType: 'level',
    isNull: 1,
    isSearch: 0,
    isAdd: 1,
    placeHolder: null,
    setting: { dataSource: ['中', '低', '高'] },
    orderId: 2,
    templateId: '2e90e499-d982-46f8-b746-e1a8ab14282c',
    templateName: '新用户引导',
    defaultValue: null,
    enabled: 1,
    guideProfessions: [],
    isGuideData: false,
    isAppShow: 0,
    guideData: false,
  },
  {
    id: '43f31c6b-592b-11eb-9baf-00163e0d174e',
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'task',
    isSystem: 1,
    fieldName: 'planTime',
    displayName: '计划时间',
    formType: 'planTime',
    isNull: 0,
    isSearch: 0,
    isAdd: 1,
    placeHolder: null,
    setting: { dataSource: null, dateType: 'dateTime' },
    orderId: 3,
    templateId: '2e90e499-d982-46f8-b746-e1a8ab14282c',
    templateName: '新用户引导',
    defaultValue: null,
    enabled: 1,
    guideProfessions: [],
    isGuideData: false,
    isAppShow: 0,
    guideData: false,
  },
  {
    id: '43f406f4-592b-11eb-9baf-00163e0d174e',
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'task',
    isSystem: 1,
    fieldName: 'description',
    displayName: '描述',
    formType: 'description',
    isNull: 1,
    isSearch: 0,
    isAdd: 1,
    placeHolder: null,
    setting: {},
    orderId: 4,
    templateId: '2e90e499-d982-46f8-b746-e1a8ab14282c',
    templateName: '新用户引导',
    defaultValue: null,
    enabled: 1,
    guideProfessions: [],
    isGuideData: false,
    isAppShow: 0,
    guideData: false,
  },
];

const taskState = {
  isCopyTask: false,
  isFromPlan: false,
  isFromEvent: false,
  isTaskCreate: true,
  isTaskEdit: false,
  isPlanTaskEdit: false,
  isFromCustomer: false,
  isFromProduct: false,
  isDisabledTaskType: false,
};

const taskTypes = [
  {
    id: '2e90e499-d982-46f8-b746-e1a8ab14282c',
    name: '新用户引导',
    enabled: 1,
    flowSetting: {
      create: { state: true, overTime: 0, approvers: [] },
      allot: { state: true, overTime: 0, approvers: [], leader: 'none' },
      accept: { state: true, overTime: 0, approvers: [] },
      start: { state: true, overTime: 0, approvers: [], leader: 'none' },
      finish: { state: true, overTime: 0, approvers: [], leader: 'none' },
      cost: { state: true, overTime: 0, approvers: [], leader: 'none' },
      review: { state: false, overTime: 0, approvers: [], leader: 'none' },
      autoReview: { state: true, overTime: 0, approvers: [] },
      close: { state: true, overTime: 0, approvers: [], leader: 'none' },
      off: { state: true, overTime: 0, approvers: [], leader: 'none' },
    },
    createTime: 1610932792000,
    isDelete: 0,
    cardSetting: {},
    overTimeSetting: { isAhead: 1, minutes: 15, reminders: [] },
    allowPause: 1,
    pauseApprovers: [],
    options: {
      showAttachment: true,
      showSparepart: true,
      showService: true,
      customerSign: true,
      showDiscountCost: true,
      serviceReport: true,
      srSysTemplate: true,
      printTask: true,
      ptSysTemplate: true,
      editUnitPrice: false,
      receiptAttNotNull: false,
      sparepartNotNull: false,
      serviceNotNull: false,
      receiptSignNotNull: false,
    },
    reportSetting: {
      tenantFields: ['name', 'phone', 'email', 'address', 'portal'],
      customerFields: ['name', 'product', 'address', 'linkman'],
      taskFields: ['taskNo', 'planTime', 'executor'],
      receiptFields: ['sparepart', 'service', 'autograph'],
      templates: null,
    },
    printSetting: {},
    planRemindSetting: { state: true, minutes: 15 },
    delayBack: 'true',
    delayBackMin: 5,
    isLeader: '2',
    noticeLeader: null,
    noticeUsers: [],
    tags: [],
    labels: [],
    professions: [],
    description: null,
    orderId: 0,
    guideProfessions: [],
    isGuideData: false,
    config: {
      positionExceptionConfig: {
        attUploadLimitMobile: false,
        positionExceptionFlag: false,
        exceptionRange: 0,
        exceptionFlagFlows: ['start', 'finish'],
        photoWatermark: false,
        watermarkContent: ['name', 'time', 'position'],
        watermarkPosition: 'topLeft',
      },
      autographMaxCount: 3,
      color: 'rgb(115, 127, 124)',
      formUser: null,
      taskTimeState: 1,
    },
    guideData: false,
  },
];

const taskUrlParams = { defaultTypeId: '2e90e499-d982-46f8-b746-e1a8ab14282c' };

const taskValue = {
  id: null,
  taskNo: null,
  templateName: '默认工单',
  customer: [],
  linkman: [],
  address: [],
  product: [],
  level: '中',
  planTime: '',
  description: '',
};

const taskTask = {
  id: null,
  taskNo: null,
  name: null,
  customer: null,
  type: null,
  level: null,
  serviceType: null,
  serviceContent: null,
  description: null,
  state: null,
  createTime: null,
  executorId: null,
  executor: null,
  synergies: [],
  attribute: {},
  balanceAttribute: {},
  createUserId: null,
  createUser: null,
  attachment: [],
  isEncryptAttachment: false,
  planTime: null,
  isEncryptPlanTime: false,
  isReview: 0,
  degree: null,
  suggestion: null,
  balanceConfirm: 0,
  balanceTime: null,
  balanceUserId: null,
  balanceUser: null,
  remark: [],
  receiptContent: null,
  product: null,
  productId: null,
  completeTime: null,
  startTime: null,
  startOn: 1,
  autograph: null,
  autographUrl: null,
  reviewTime: null,
  reviewUserId: null,
  reviewUser: null,
  tenantId: null,
  allotTime: null,
  allotUserId: null,
  allotUser: null,
  acceptTime: null,
  closeTime: null,
  taddress: {},
  isEncryptTaddress: false,
  tlmId: null,
  tlmName: null,
  tlmPhone: null,
  tversion: null,
  inTaskPool: 0,
  updateTime: null,
  products: [],
  evaluate: null,
  evaluateContent: null,
  evaluateSource: null,
  profit: null,
  sale: null,
  cost: null,
  templateId: '1',
  templateName: '默认工单',
  cardInfo: [],
  inApprove: 0,
  isPaused: 0,
  overTime: null,
  isOverTime: 0,
  taskUsedTime: null,
  taskUsedTimeStr: '',
  acceptUsedTime: null,
  acceptUsedTimeStr: '',
  workUsedTime: null,
  workUsedTimeStr: '',
  onceOverTime: 0,
  taskResponseTime: null,
  taskResponseTimeStr: '',
  expenseDetail: null,
  isDelete: null,
  settlement: null,
  sparepart: null,
  onceRefused: 0,
  oncePaused: 0,
  allotType: 0,
  allotTypeStr: '',
  onceReallot: 0,
  positionException: 0,
  oncePrinted: 0,
  onceRollback: 0,
  validAddress: false,
  expenseSheet: null,
  evaluateObj: null,
  source: null,
  eventId: null,
  eventNo: null,
  guideProfessions: [],
  isGuideData: false,
  isSettled: -1,
  isReviewed: -1,
  isEvaluated: -1,
  isClosed: -1,
  tick: null,
  taddressStr: null,
  guideData: false,
  v2: false,
};

const taskAllotFields = [
  {
    id: 'eb8028ae-3511-11eb-9baf-00163e0d174e',
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'task',
    isSystem: 1,
    fieldName: 'taskNo',
    displayName: '工单编号',
    formType: 'taskNo',
    isNull: 0,
    isSearch: 1,
    isAdd: 1,
    placeHolder: '工单编号将在创建后由系统生成',
    setting: {},
    orderId: 0,
    templateId: '32e8ce90-5173-4f08-b24a-927cd58a9124',
    templateName: '工单复测',
    defaultValue: null,
    enabled: 1,
    guideProfessions: [],
    isGuideData: false,
    isAppShow: 0,
    guideData: false,
  },
  {
    id: 'eb814bbd-3511-11eb-9baf-00163e0d174e',
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'task',
    isSystem: 1,
    fieldName: 'customer',
    displayName: '客户',
    formType: 'customer',
    isNull: 0,
    isSearch: 1,
    isAdd: 1,
    placeHolder: '请选择客户或新建客户',
    setting: {
      customerOption: { product: true, address: true, linkman: true },
    },
    orderId: 1,
    templateId: '32e8ce90-5173-4f08-b24a-927cd58a9124',
    templateName: '工单复测',
    defaultValue: null,
    enabled: 1,
    guideProfessions: [],
    isGuideData: false,
    isAppShow: 0,
    guideData: false,
  },
  {
    id: 'eb8243af-3511-11eb-9baf-00163e0d174e',
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'task',
    isSystem: 1,
    fieldName: 'level',
    displayName: '优先级',
    formType: 'level',
    isNull: 1,
    isSearch: 0,
    isAdd: 1,
    placeHolder: null,
    setting: { dataSource: ['中', '低', '高'] },
    orderId: 2,
    templateId: '32e8ce90-5173-4f08-b24a-927cd58a9124',
    templateName: '工单复测',
    defaultValue: null,
    enabled: 1,
    guideProfessions: [],
    isGuideData: false,
    isAppShow: 0,
    guideData: false,
  },
  {
    id: 'eb8336a7-3511-11eb-9baf-00163e0d174e',
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'task',
    isSystem: 1,
    fieldName: 'serviceType',
    displayName: '服务类型',
    formType: 'serviceType',
    isNull: 1,
    isSearch: 0,
    isAdd: 1,
    placeHolder: null,
    setting: { dataSource: ['保内免费', '保内收费', '保外免费', '保外收费'] },
    orderId: 3,
    templateId: '32e8ce90-5173-4f08-b24a-927cd58a9124',
    templateName: '工单复测',
    defaultValue: null,
    enabled: 1,
    guideProfessions: [],
    isGuideData: false,
    isAppShow: 0,
    guideData: false,
  },
  {
    id: 'eb8425e4-3511-11eb-9baf-00163e0d174e',
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'task',
    isSystem: 1,
    fieldName: 'serviceContent',
    displayName: '服务内容',
    formType: 'serviceContent',
    isNull: 1,
    isSearch: 0,
    isAdd: 1,
    placeHolder: null,
    setting: { dataSource: ['安装', '维修', '保养', '巡检', '检查'] },
    orderId: 4,
    templateId: '32e8ce90-5173-4f08-b24a-927cd58a9124',
    templateName: '工单复测',
    defaultValue: null,
    enabled: 1,
    guideProfessions: [],
    isGuideData: false,
    isAppShow: 0,
    guideData: false,
  },
  {
    id: 'eb853f8b-3511-11eb-9baf-00163e0d174e',
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'task',
    isSystem: 1,
    fieldName: 'planTime',
    displayName: '计划时间',
    formType: 'planTime',
    isNull: 0,
    isSearch: 0,
    isAdd: 1,
    placeHolder: null,
    setting: { dataSource: null, dateType: 'dateTime' },
    orderId: 5,
    templateId: '32e8ce90-5173-4f08-b24a-927cd58a9124',
    templateName: '工单复测',
    defaultValue: null,
    enabled: 1,
    guideProfessions: [],
    isGuideData: false,
    isAppShow: 0,
    guideData: false,
  },
  {
    id: 'eb86310b-3511-11eb-9baf-00163e0d174e',
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'task',
    isSystem: 1,
    fieldName: 'description',
    displayName: '描述',
    formType: 'description',
    isNull: 1,
    isSearch: 0,
    isAdd: 1,
    placeHolder: null,
    setting: {},
    orderId: 6,
    templateId: '32e8ce90-5173-4f08-b24a-927cd58a9124',
    templateName: '工单复测',
    defaultValue: null,
    enabled: 1,
    guideProfessions: [],
    isGuideData: false,
    isAppShow: 0,
    guideData: false,
  },
  {
    id: 'eb872089-3511-11eb-9baf-00163e0d174e',
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'task',
    isSystem: 1,
    fieldName: 'attachment',
    displayName: '附件',
    formType: 'attachment',
    isNull: 1,
    isSearch: 0,
    isAdd: 1,
    placeHolder: null,
    setting: {},
    orderId: 7,
    templateId: '32e8ce90-5173-4f08-b24a-927cd58a9124',
    templateName: '工单复测',
    defaultValue: null,
    enabled: 1,
    guideProfessions: [],
    isGuideData: false,
    isAppShow: 0,
    guideData: false,
  },
  {
    displayName: '负责人',
    fieldName: 'executor',
    formType: 'user',
    isSystem: 1,
  },
  { displayName: '协同人', fieldName: 'synergies', isSystem: 1 },
  { displayName: '完成时间', fieldName: 'completeTime', formType: 'timestamp' },
  { displayName: '满意度', fieldName: 'degree' },
  { displayName: '工单状态', fieldName: 'state' },
  {
    displayName: '创建人',
    fieldName: 'createUser',
    formType: 'user',
    isSystem: 1,
  },
  {
    displayName: '创建时间',
    fieldName: 'createTime',
    formType: 'timestamp',
    isSystem: 1,
  },
  {
    displayName: '派单人',
    fieldName: 'allotUser',
    formType: 'user',
    isSystem: 1,
  },
  {
    displayName: '创建方式',
    fieldName: 'source',
    formType: 'user',
    isSystem: 1,
  },
];

const taskAllotTask = {
  id: 'dde25e41-4a6e-11eb-9baf-00163e0d174e',
  taskNo: 'TDG2820120143',
  name: null,
  customer: {
    createUser: 'd232a388-f8ab-11ea-9baf-00163e0d174e',
    updateUser: null,
    createTime: null,
    updateTime: null,
    id: '075e7978-efb9-4eae-bbf3-d6f8dcce1b79',
    name: '沐籽',
    enName: null,
    serialNumber: 'CUSQF02179',
    status: null,
    level: null,
    superior: null,
    teamId: null,
    customerManager: '4c67e321-45e9-11eb-9baf-00163e0d174e',
    customerManagerName: '沐籽',
    remark: null,
    industry: null,
    type: null,
    taskCount: null,
    productCount: null,
    isDelete: null,
    attribute: {},
    companyNature: null,
    tagIds: null,
    tags: [{ id: '6f51dd10-354f-11eb-9baf-00163e0d174e', tagName: '沐籽团队' }],
    createUserId: null,
    createLoginUser: null,
    lmName: '沐籽',
    lmPhone: '15669089475',
    lmEmail: null,
    customerAddress: {
      adCountry: '',
      adDist: '平定县',
      adProvince: '山西省',
      adCity: '阳泉市',
      adAddress: '',
      adLongitude: 113.657841,
      adLatitude: 37.786653,
      addressType: 0,
      validAddress: true,
    },
    source: null,
    guideProfessions: [],
    isGuideData: false,
    products: [],
    guideData: false,
    focus: false,
  },
  type: null,
  level: '中',
  serviceType: '保内免费',
  serviceContent: '安装',
  description: null,
  state: 'created',
  createTime: 1609312559000,
  executorId: null,
  executor: null,
  synergies: [],
  attribute: {},
  balanceAttribute: {},
  createUserId: '4c67e321-45e9-11eb-9baf-00163e0d174e',
  createUser: {
    userId: '4c67e321-45e9-11eb-9baf-00163e0d174e',
    loginName: null,
    displayName: '沐籽',
    email: null,
    cellPhone: null,
    lastLoginTime: null,
    enabled: 1,
    weixinid: null,
    powercode: null,
    head:
      'https://static-legacy.dingtalk.com/media/lADPD3lGsVeCKWTNBDjNBDg_1080_1080.jpg',
    sex: null,
    firstLogin: 0,
    tagList: [],
    departments: null,
    roles: null,
    attribute: {},
    openid: '$:LWCP_v1:$t5u9ZS/AA3u1fUUtiMiOrQ==',
    longitude: null,
    latitude: null,
    isDelete: null,
    synOpenid: null,
    staffId: '1765463702893421',
    tenantId: null,
    mainTeamId: null,
    unfinishedTask: null,
    todayFinishedTask: null,
    state: null,
    cusDistance: null,
    wechat: null,
    superAdmin: null,
    isTeamLeader: 0,
  },
  attachment: [],
  isEncryptAttachment: false,
  planTime: '2021-01-02 19:45:00',
  isEncryptPlanTime: false,
  isReview: 0,
  degree: null,
  suggestion: null,
  balanceConfirm: 0,
  balanceTime: null,
  balanceUserId: null,
  balanceUser: null,
  remark: [],
  receiptContent: null,
  product: null,
  productId: null,
  completeTime: null,
  startTime: null,
  startOn: 1,
  autograph: null,
  autographUrl: null,
  reviewTime: null,
  reviewUserId: null,
  reviewUser: null,
  tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
  allotTime: null,
  allotUserId: null,
  allotUser: null,
  acceptTime: null,
  closeTime: null,
  taddress: {
    id: 'd3a5beb8-4030-11eb-9baf-00163e0d174e',
    city: '阳泉市',
    dist: '平定县',
    address: '',
    latitude: 37.786653,
    province: '山西省',
    longitude: 113.657841,
  },
  isEncryptTaddress: false,
  tlmId: 'd3a67032-4030-11eb-9baf-00163e0d174e',
  tlmName: '沐籽',
  tlmPhone: '15669089475',
  tversion: 'v2',
  inTaskPool: 0,
  updateTime: 1609312559000,
  products: [
    {
      id: 'cf58340c-4a6a-11eb-9baf-00163e0d174e',
      name: '沐籽测试004(勿动）',
      type: '保健品',
      serialNumber: '01010100011',
    },
  ],
  evaluate: null,
  evaluateContent: null,
  evaluateSource: null,
  profit: null,
  sale: null,
  cost: null,
  templateId: '32e8ce90-5173-4f08-b24a-927cd58a9124',
  templateName: '工单复测',
  cardInfo: [],
  inApprove: 0,
  isPaused: 0,
  overTime: null,
  isOverTime: 0,
  taskUsedTime: null,
  taskUsedTimeStr: '',
  acceptUsedTime: null,
  acceptUsedTimeStr: '',
  workUsedTime: null,
  workUsedTimeStr: '',
  onceOverTime: 0,
  taskResponseTime: null,
  taskResponseTimeStr: '',
  expenseDetail: null,
  isDelete: 0,
  settlement: null,
  sparepart: null,
  onceRefused: 0,
  oncePaused: 0,
  allotType: 0,
  allotTypeStr: '',
  onceReallot: 0,
  positionException: 0,
  oncePrinted: 0,
  onceRollback: 0,
  validAddress: true,
  expenseSheet: null,
  evaluateObj: null,
  source: '手动创建',
  eventId: null,
  eventNo: null,
  guideProfessions: [],
  isGuideData: false,
  isSettled: -1,
  isReviewed: -1,
  isEvaluated: -1,
  isClosed: -1,
  tick: null,
  taddressStr: '山西省,阳泉市,平定县',
  guideData: false,
  v2: true,
};

const taskAllotLoginUser = {
  head:
    'https://static-legacy.dingtalk.com/media/lADPD3lGo1ZeoWfNBDjNBDg_1080_1080.jpg',
  displayName: '德芙*',
  roles: ['1'],
  tagIds: [],
  userId: '94f920b1-ee5e-11ea-879a-00163e0f1a1b',
  staffId: '1464241215763871217',
  authorities: {
    TASK_ADD: 3,
    PRODUCT_CREATE: 3,
    CUSTOMER_CREATE: 3,
    VIP_PAYMENT_ONLINE: 3,
    TASK_BATCH_DISPATCH: 3,
    CASE_ADD: 3,
    SERVICE_CREATE: 3,
    CALLCENTER_EDIT: 3,
    CASE_VIEW: 3,
    CALLCENTER_VIEW: 3,
    TASK_EDIT: 3,
    TASK_FEEDBACK: 3,
    VIP_INFO_NOTICE_SELECT: 3,
    LOGIN_PC: 3,
    PRODUCT_CATALOG_VIEW: 3,
    VIP_INFO_NOTICE_CREATE: 3,
    SERVICE_EDIT: 3,
    PORTAL_ORDER: 3,
    PRODUCT_EDIT: 3,
    VIP_SPAREPART_BACK: 3,
    TASK_DISPATCH: 3,
    REPORT_VIEW: 3,
    TASK_POOL: 3,
    VIP_REPORT_VIEW: 3,
    TASK_VIEW: 3,
    AUTH_STAFF: 3,
    PRODUCT_CATALOG_DELETE: 3,
    AUTH_ROLE: 3,
    TASK_CLOSE: 3,
    TASK_BATCH_CLOSE: 3,
    VIP_SPAREPART_PERSION: 3,
    INFO_EDIT: 3,
    VIP_SPAREPART_INOUT: 3,
    TASK_AUDIT: 3,
    PRODUCT_VIEW: 3,
    CUSTOMER_DELETE: 3,
    CASE_DELETE: 3,
    INFO_VIEW: 3,
    EXPORT_IN: 3,
    VIP_APPROVE: 3,
    PART_EDIT: 3,
    SERVICE_VIEW: 3,
    CUSTOMER_VIEW: 3,
    VIP_SPAREPART_CREATE: 3,
    VIP_SPAREPART_VIEW: 3,
    CUSTOMER_PQRCODE: 3,
    TASK_DELETE: 3,
    VIP_TASK_PLAN: 3,
    CALLCENTER_STATISTICS: 3,
    PRODUCT_DELETE: 3,
    PRODUCT_CATALOG_CREATE: 3,
    CASE_EDIT: 3,
    VIP_INFO_CREATE: 3,
    SYSTEM_SEETING: 3,
    LOGIN_YD: 3,
    VIP_SPAREPART_EDIT: 3,
    PART_VIEW: 3,
    AUTH_TAG: 3,
    VIP_SPAREPART_STOCK: 3,
    PRODUCT_CATALOG_EDIT: 3,
    TASK_BATCH_AUDIT: 3,
    CUSTOMER_EDIT: 3,
  },
  tagIdsWithChildTag: [],
};

const taskAccountFields = [
  {
    fieldId: '330623',
    tableName: 'balance',
    isSystem: 0,
    fieldName: 'field_lXuGw0Tm',
    displayName: '结算周期',
    formType: 'text',
    defaultValue: null,
    maxLength: 0,
    dotLength: 0,
    isNull: 1,
    isValidate: 0,
    enabled: false,
    isSearch: 0,
    isAdd: 1,
    isReadonly: 0,
    placeHolder: '请填写结算周期',
    setting: { dataSource: '', isOpen: true },
    orderId: 0,
    tableChsName: null,
  },
  {
    fieldId: '330624',
    tableName: 'balance',
    isSystem: 0,
    fieldName: 'field_Z2xFhEL0',
    displayName: '结算方法',
    formType: 'select',
    defaultValue: null,
    maxLength: 0,
    dotLength: 0,
    isNull: 1,
    isValidate: 0,
    enabled: false,
    isSearch: 0,
    isAdd: 1,
    isReadonly: 0,
    placeHolder: '请选择结算方法',
    setting: {
      dataSource: ['结算方法1', '结算方法2'],
      isOpen: true,
    },
    orderId: 1,
    tableChsName: null,
  },
  {
    fieldId: '330625',
    tableName: 'balance',
    isSystem: 0,
    fieldName: 'field_FSv7r0Ws',
    displayName: '结算金额',
    formType: 'text',
    defaultValue: null,
    maxLength: 0,
    dotLength: 0,
    isNull: 0,
    isValidate: 0,
    enabled: false,
    isSearch: 0,
    isAdd: 1,
    isReadonly: 0,
    placeHolder: '请填写结算金额',
    setting: { dataSource: '', isOpen: true },
    orderId: 2,
    tableChsName: null,
  },
  {
    fieldId: '330626',
    tableName: 'balance',
    isSystem: 0,
    fieldName: 'field_vWRrxoqx',
    displayName: '结算类别',
    formType: 'select',
    defaultValue: null,
    maxLength: 0,
    dotLength: 0,
    isNull: 1,
    isValidate: 0,
    enabled: false,
    isSearch: 0,
    isAdd: 1,
    isReadonly: 0,
    placeHolder: '请选择结算类别',
    setting: { dataSource: ['基本户', '一般户', '支付宝'], isOpen: true },
    orderId: 3,
    tableChsName: null,
  },
  {
    fieldId: '330627',
    tableName: 'balance',
    isSystem: 0,
    fieldName: 'field_SWi1eybh',
    displayName: '结算选项',
    formType: 'select',
    defaultValue: null,
    maxLength: 0,
    dotLength: 0,
    isNull: 1,
    isValidate: 0,
    enabled: false,
    isSearch: 0,
    isAdd: 1,
    isReadonly: 0,
    placeHolder: '请选择结算选项',
    setting: { dataSource: ['已结账', '季度结账', '年结账'], isOpen: true },
    orderId: 4,
    tableChsName: null,
  },
  {
    fieldId: '330628',
    tableName: 'balance',
    isSystem: 0,
    fieldName: 'field_FikMrdcC',
    displayName: '结算备注',
    formType: 'textarea',
    defaultValue: null,
    maxLength: 0,
    dotLength: 0,
    isNull: 1,
    isValidate: 0,
    enabled: false,
    isSearch: 0,
    isAdd: 1,
    isReadonly: 0,
    placeHolder: '请填写结算备注',
    setting: { dataSource: '', isOpen: true },
    orderId: 5,
    tableChsName: null,
  },
];

const taskfeedBackTask = {
  id: 'b7e0e1b4-2321-11eb-9baf-00163e0d174e',
  taskNo: 'TGH0820110029',
  name: null,
  customer: {
    createUser: 'b5d4f02b-a480-11ea-9ddd-00163e0f1a1b',
    updateUser: null,
    createTime: null,
    updateTime: null,
    id: 'ca8f7130-2257-11eb-9baf-00163e0d174e',
    name: '浩克',
    enName: null,
    serialNumber: 'CUSTS00989',
    status: null,
    level: null,
    superior: null,
    teamId: null,
    customerManager: 'f415e7d0-ed83-11ea-879a-00163e0f1a1b',
    customerManagerName: '万万',
    remark: null,
    industry: null,
    type: null,
    taskCount: null,
    productCount: null,
    isDelete: null,
    attribute: {},
    companyNature: null,
    tagIds: null,
    tags: [
      { id: '55e4851a-2326-11eb-9baf-00163e0d174e', tagName: '浩克团队的' },
    ],
    createUserId: null,
    createLoginUser: null,
    lmName: '浩克',
    lmPhone: '18072725367',
    lmEmail: null,
    customerAddress: {
      adCountry: '',
      adDist: '下城区',
      adProvince: '浙江省',
      adCity: '杭州市',
      adAddress: '西湖文化广场',
      adLongitude: 120.163733,
      adLatitude: 30.276818,
      addressType: 0,
      validAddress: true,
    },
    source: null,
    guideProfessions: [],
    isGuideData: false,
    products: [],
    guideData: false,
    focus: false,
  },
  type: null,
  level: '中',
  serviceType: '保内免费',
  serviceContent: '安装',
  description: null,
  state: 'costed',
  createTime: 1604991329000,
  executorId: null,
  executor: {
    userId: 'b5d4f02b-a480-11ea-9ddd-00163e0f1a1b',
    loginName: null,
    displayName: '贾权超',
    email: null,
    cellPhone: null,
    lastLoginTime: null,
    enabled: 1,
    weixinid: null,
    powercode: null,
    head:
      'https://static-legacy.dingtalk.com/media/lADPGojJ8b586_nNA8LNA8A_960_962.jpg',
    sex: null,
    firstLogin: 0,
    tagList: [],
    departments: null,
    roles: null,
    attribute: {},
    openid: '$:LWCP_v1:$jpkKb+WzVcFor60ollVPxOymzVXUfqxh',
    longitude: null,
    latitude: null,
    isDelete: null,
    synOpenid: null,
    staffId: '196230552935603552',
    tenantId: null,
    mainTeamId: null,
    unfinishedTask: null,
    todayFinishedTask: null,
    state: null,
    cusDistance: null,
    wechat: null,
    superAdmin: null,
    isTeamLeader: 0,
  },
  synergies: [
    {
      head:
        'https://static-legacy.dingtalk.com/media/lADPGp4a6wojtZrNBDjNAmM_611_1080.jpg',
      userId: 'b6f2a939-0edc-11eb-9baf-00163e0d174e',
      staffId: '11676958591269648',
      displayName: '鳌拜',
    },
  ],
  attribute: {
    customReceipt: 'true',
    paymentMethod: '',
    field_Fpx5eCWPQWH4v5Uw: null,
    field_lv341AYTQt7em3BE: '我在这里等你',
    field_o0ugvNqwhlMOK6UN: null,
  },
  balanceAttribute: {
    field_FSv7r0Ws: '123',
    field_FikMrdcC: '',
    field_SWi1eybh: '',
    field_Z2xFhEL0: '',
    field_lXuGw0Tm: '周期12312313',
    field_vWRrxoqx: '',
    field_0HTNjMJ1: [],
  },
  createUserId: 'b5d4f02b-a480-11ea-9ddd-00163e0f1a1b',
  createUser: {
    userId: 'b5d4f02b-a480-11ea-9ddd-00163e0f1a1b',
    loginName: null,
    displayName: '贾权超',
    email: null,
    cellPhone: null,
    lastLoginTime: null,
    enabled: 1,
    weixinid: null,
    powercode: null,
    head:
      'https://static-legacy.dingtalk.com/media/lADPGojJ8b586_nNA8LNA8A_960_962.jpg',
    sex: null,
    firstLogin: 0,
    tagList: [],
    departments: null,
    roles: null,
    attribute: {},
    openid: '$:LWCP_v1:$jpkKb+WzVcFor60ollVPxOymzVXUfqxh',
    longitude: null,
    latitude: null,
    isDelete: null,
    synOpenid: null,
    staffId: '196230552935603552',
    tenantId: null,
    mainTeamId: null,
    unfinishedTask: null,
    todayFinishedTask: null,
    state: null,
    cusDistance: null,
    wechat: null,
    superAdmin: null,
    isTeamLeader: 0,
  },
  attachment: [
    {
      filename: '大西瓜-贾权超-2020-11-10.jpg',
      id: 'c5c566a1-29d7-4129-9d9d-20c6f2fa9169',
      url:
        'https://she-dev.oss-cn-hangzhou.aliyuncs.com/acs/newfiles/2fe245f4-31f0-11ea-9ddd-00163e0f1a1b/202011/4a6dac58-691a-4271-9618-2098f2566e38.jpg',
      fileSize: '1.04MB',
      receipt: true,
    },
  ],
  isEncryptAttachment: false,
  planTime: '2020-11-12 00:00:00',
  isEncryptPlanTime: false,
  isReview: 0,
  degree: null,
  suggestion: null,
  balanceConfirm: 1,
  balanceTime: 1606459920000,
  balanceUserId: 'b6f2a939-0edc-11eb-9baf-00163e0d174e',
  balanceUser: {
    userId: 'b6f2a939-0edc-11eb-9baf-00163e0d174e',
    loginName: null,
    displayName: '鳌拜',
    email: null,
    cellPhone: null,
    lastLoginTime: null,
    enabled: 1,
    weixinid: null,
    powercode: null,
    head: null,
    sex: null,
    firstLogin: 0,
    tagList: [],
    departments: null,
    roles: null,
    attribute: {},
    openid: null,
    longitude: null,
    latitude: null,
    isDelete: null,
    synOpenid: null,
    staffId: null,
    tenantId: null,
    mainTeamId: null,
    unfinishedTask: null,
    todayFinishedTask: null,
    state: null,
    cusDistance: null,
    wechat: null,
    superAdmin: null,
    isTeamLeader: 0,
  },
  remark: [],
  receiptContent: '',
  product: null,
  productId: null,
  completeTime: 1604992344000,
  startTime: 1604991366000,
  startOn: 1,
  autograph: null,
  autographUrl: null,
  reviewTime: null,
  reviewUserId: null,
  reviewUser: null,
  tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
  allotTime: 1604991355000,
  allotUserId: 'b5d4f02b-a480-11ea-9ddd-00163e0f1a1b',
  allotUser: {
    userId: 'b5d4f02b-a480-11ea-9ddd-00163e0f1a1b',
    loginName: null,
    displayName: '贾权超',
    email: null,
    cellPhone: null,
    lastLoginTime: null,
    enabled: 1,
    weixinid: null,
    powercode: null,
    head:
      'https://static-legacy.dingtalk.com/media/lADPGojJ8b586_nNA8LNA8A_960_962.jpg',
    sex: null,
    firstLogin: 0,
    tagList: [],
    departments: null,
    roles: null,
    attribute: {},
    openid: null,
    longitude: null,
    latitude: null,
    isDelete: null,
    synOpenid: null,
    staffId: '196230552935603552',
    tenantId: null,
    mainTeamId: null,
    unfinishedTask: null,
    todayFinishedTask: null,
    state: null,
    cusDistance: null,
    wechat: null,
    superAdmin: null,
    isTeamLeader: 0,
  },
  acceptTime: 1604991363000,
  closeTime: null,
  taddress: {
    id: 'ca94425b-2257-11eb-9baf-00163e0d174e',
    city: '杭州市',
    dist: '下城区',
    address: '西湖文化广场',
    latitude: 30.276818,
    province: '浙江省',
    longitude: 120.163733,
  },
  isEncryptTaddress: false,
  tlmId: 'ca967593-2257-11eb-9baf-00163e0d174e',
  tlmName: '浩克',
  tlmPhone: '18072725367',
  tversion: 'v2',
  inTaskPool: 0,
  updateTime: 1606459920000,
  products: [],
  evaluate: null,
  evaluateContent: null,
  evaluateSource: null,
  profit: null,
  sale: null,
  cost: null,
  templateId: '3d6a1ae9-a452-4368-8e33-ac0f6de9c908',
  templateName: '鳌拜Test',
  cardInfo: [],
  inApprove: 0,
  isPaused: 0,
  overTime: null,
  isOverTime: 0,
  taskUsedTime: 981,
  taskUsedTimeStr: '0小时16分钟',
  acceptUsedTime: 8,
  acceptUsedTimeStr: '0小时01分钟',
  workUsedTime: 978,
  workUsedTimeStr: '0小时16分钟',
  onceOverTime: 0,
  taskResponseTime: 37,
  taskResponseTimeStr: '0小时01分钟',
  expenseDetail: null,
  isDelete: 0,
  settlement: null,
  sparepart: 'personalRepertory',
  onceRefused: 0,
  oncePaused: 0,
  allotType: 1,
  allotTypeStr: '手动派单',
  onceReallot: 0,
  positionException: 0,
  oncePrinted: 0,
  onceRollback: 0,
  validAddress: true,
  expenseSheet: null,
  evaluateObj: null,
  source: '由事件创建',
  eventId: null,
  eventNo: null,
  guideProfessions: [],
  isGuideData: false,
  isSettled: 1,
  isReviewed: 0,
  isEvaluated: 0,
  isClosed: -1,
  tick: null,
  taddressStr: '浙江省,杭州市,下城区,西湖文化广场',
  guideData: false,
  v2: true,
};

const taskfeedBackConfig = {
  modifyEvaluate: true,
  modifyEventEvaluate: true,
  autoCloseTask: true,
  useStarEvaluate: true,
  useTagEvaluate: true,
  starEvaluateNotNull: false,
  starEvaluateFeilds: [
    'starEvaluate1',
    'starEvaluate2',
    'starEvaluate3',
    'starEvaluate4',
    'starEvaluate5',
    'starEvaluate6',
  ],
  starEvaluates: ['服务态度', '服务效率', '服务质量'],
  tagEvaluates: ['速度快', '很热情', '质量高', '技术强', '有点差'],
  reviewViewAuthiroty: 'hasTaskViewAuthiroty',
};
const productFields = [
  {
    displayName: '从模板中选择',
    fieldName: 'template',
    formType: 'select',
    isSystem: 1,
  },
  {
    id: 83958,
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'product',
    isSystem: 1,
    fieldName: 'customer',
    displayName: '客户',
    formType: 'customer',
    defaultValue: null,
    isNull: 0,
    isSearch: 0,
    placeHolder: null,
    setting: {
      customerOption: {
        address: false,
        linkman: false,
        addressNotNull: false,
        linkmanNotNull: false,
      },
    },
    orderId: 0,
    isDelete: 0,
    guideProfessions: [
      '制造业',
      '其他',
      '建筑家居',
      '服务业',
      '互联网/IT',
      '贸易零售',
    ],
    isGuideData: false,
    isVisible: true,
    isHidden: 0,
    modifyTime: '2021-01-19T05:51:09.000+0000',
  },
  {
    id: 83964,
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'product',
    isSystem: 1,
    fieldName: 'name',
    displayName: '产品名称',
    formType: 'text',
    defaultValue: null,
    isNull: 0,
    isSearch: 0,
    placeHolder: '胡家是否康复回家啊饭卡',
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [
      '制造业',
      '其他',
      '建筑家居',
      '服务业',
      '互联网/IT',
      '贸易零售',
    ],
    isGuideData: false,
    isVisible: true,
    isHidden: 0,
    modifyTime: '2020-12-31T03:36:43.000+0000',
  },
  {
    id: 83965,
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'product',
    isSystem: 1,
    fieldName: 'serialNumber',
    displayName: '产品编号',
    formType: 'text',
    defaultValue: null,
    isNull: 0,
    isSearch: 0,
    placeHolder: '',
    setting: { serialNumberUnique: true },
    orderId: 2,
    isDelete: 0,
    guideProfessions: [
      '制造业',
      '其他',
      '建筑家居',
      '服务业',
      '互联网/IT',
      '贸易零售',
    ],
    isGuideData: false,
    isVisible: true,
    isHidden: 0,
    modifyTime: '2021-01-19T05:51:09.000+0000',
  },
  {
    id: 83966,
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'product',
    isSystem: 1,
    fieldName: 'catalogId',
    displayName: '产品类型',
    justGuide: true,
    formType: 'related_catalog',
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: '请选择闭环合并',
    setting: {
      isMulti: false,
      dataSource: [
        '液压机',
        '传动设备',
        '电力设备',
        '检测设备',
        '其他设备',
        '运动器材',
      ],
    },
    orderId: 3,
    isDelete: 0,
    guideProfessions: [
      '制造业',
      '其他',
      '建筑家居',
      '服务业',
      '互联网/IT',
      '贸易零售',
    ],
    isGuideData: false,
    isVisible: true,
    isHidden: 0,
    modifyTime: '2021-01-19T05:51:09.000+0000',
  },
  {
    id: 85606,
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'product',
    isSystem: 0,
    fieldName: 'field_MxlPpbgCr6RVAln6',
    displayName: '日期',
    formType: 'date',
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 4,
    isDelete: 0,
    guideProfessions: [],
    isGuideData: false,
    isVisible: true,
    isHidden: 0,
    modifyTime: '2021-01-19T05:51:09.000+0000',
  },
  {
    id: 85609,
    tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
    tableName: 'product',
    isSystem: 0,
    fieldName: 'field_nUs5iyoXzhNjV2aK',
    displayName: '位置',
    formType: 'location',
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 5,
    isDelete: 0,
    guideProfessions: [],
    isGuideData: false,
    isVisible: true,
    isHidden: 0,
    modifyTime: '2021-01-19T05:51:09.000+0000',
  },
];
const productValue = {
  name: '',
  serialNumber: '',
  customer: [],
  template: [],
  linkman: [],
  customerAddress: [],
  catalogId: [],
  field_MxlPpbgCr6RVAln6: '',
  field_nUs5iyoXzhNjV2aK: '',
};

const productSerachCustomer = {
  pageNum: 1,
  pageSize: 10,
  size: 1,
  orderBy: null,
  startRow: 1,
  endRow: 0,
  total: 1,
  pages: 1,
  list: [
    {
      id: '1970b15c-4a91-11eb-9baf-00163e0d174e',
      label: '张三',
      value: '1970b15c-4a91-11eb-9baf-00163e0d174e',
      lmPhone: '13100890980',
      lmName: '张三',
      serialNumber: 'CUSVH02194',
      customerAddress: {
        adCountry: null,
        adDist: null,
        adProvince: null,
        adCity: null,
        adAddress: null,
        adLongitude: null,
        adLatitude: null,
        addressType: 0,
        validAddress: false,
      },
    },
  ],
  firstPage: 0,
  prePage: 0,
  nextPage: 0,
  lastPage: 0,
  isFirstPage: true,
  isLastPage: true,
  hasPreviousPage: false,
  hasNextPage: false,
  navigatePages: 0,
  navigatepageNums: null,
};
const productSearchTemplate = {
  pageNum: 1,
  pageSize: 10,
  size: 7,
  startRow: 1,
  endRow: 7,
  total: 7,
  pages: 1,
  list: [
    {
      label: '电冰箱',
      value: 'a33744da-ee01-478d-bd8f-f21c72f23d07',
      id: 'a33744da-ee01-478d-bd8f-f21c72f23d07',
      tenantId: null,
      name: '电冰箱',
      serialNumber: 'KT23455',
      type: '电器',
      createUser: {
        userId: 'f415e7d0-ed83-11ea-879a-00163e0f1a1b',
        tenantId: null,
        loginName: null,
        loginPassword: null,
        salt: null,
        displayName: '万万',
        email: null,
        cellPhone: null,
        lastLoginTime: null,
        enabled: null,
        weixinid: null,
        powercode: null,
        firstLogin: null,
        tagList: [],
        departments: null,
        roles: null,
        superAdmin: null,
        head: null,
        sex: null,
        openid: null,
        longitude: null,
        latitude: null,
        isDelete: null,
        synOpenid: null,
        staffId: null,
        createTime: null,
        updateTime: null,
        state: null,
        mainTeamId: null,
        ua: null,
        attribute: {},
        cusDistance: null,
        unfinishedTask: null,
        todayFinishedTask: null,
        isTeamLeader: 0,
      },
      createUserId: 'f415e7d0-ed83-11ea-879a-00163e0f1a1b',
      createTime: '2020-12-17T02:27:49.000+0000',
      isDelete: 0,
      attribute: {
        field_AQRqZSxFFYiyY4ZW: '单行文本',
        field_mOl2aJrw69KpPRCU: '1',
        field_8LQOHkwI1fEx1UK8: '1',
        field_DUtZDtBAShIRICrv: '1',
        field_2w5nPNtueWa7Geeg: '1',
        field_gPtVMAqsm8PNGTc7: '1',
        field_3UdYzKTfMszyeMnV: '1',
        field_IVcSmvo1kdTsQ9hv: '1',
        field_T6D26lV54fAY8OXA: '1',
        field_FuQwDI1lYxRnR74C: '4',
        field_gq6gihok5VkksePI: '1',
        field_2qYBGAT0r7R9R4m8: ['5', '6'],
        field_DnjPe2qsraCwynk5: ['一', '二'],
        field_g4boRtIXKfrg1p6B: '2018-01-01',
        field_QXASFcIJTqenhxyD: '2018-01',
        field_qFNAnQ1nEsj3lm8M: '2018-01-01 00:00:00',
        field_OMeGC7fDCJIRbPSF: '123123',
      },
      iid: null,
    },
  ],
  prePage: 0,
  nextPage: 0,
  isFirstPage: true,
  isLastPage: true,
  hasPreviousPage: false,
  hasNextPage: false,
  navigatePages: 8,
  navigatepageNums: [1],
  navigateFirstPage: 1,
  navigateLastPage: 1,
  lastPage: 1,
  firstPage: 1,
};

const productSearchCatalog = {
  pageNum: 1,
  pageSize: 50,
  size: 20,
  startRow: 1,
  endRow: 20,
  total: 2,
  pages: 1,
  list: [
    {
      id: 75,
      tenantId: '2fe245f4-31f0-11ea-9ddd-00163e0f1a1b',
      parentId: null,
      catalogName: '电器',
      catalogNum: 'PPN000058',
      productDesc: null,
      productVideo: [],
      productPic: [],
      thumbnail: [],
      productExplain: [],
      attribute: {},
      pathName: '电器',
      label: '电器',
      isDelete: 0,
      showList: 1,
      conData: 0,
      orderId: 3,
      source: 0,
      createUserId: '83e6e320-32f2-11eb-9baf-00163e0d174e',
      createTime: '2020-12-28 19:48:46',
      updateUserId: '83e6e320-32f2-11eb-9baf-00163e0d174e',
      updateTime: '2020-12-28 19:48:46',
    },
  ],
  prePage: 0,
  nextPage: 0,
  isFirstPage: true,
  isLastPage: true,
  hasPreviousPage: false,
  hasNextPage: false,
  navigatePages: 8,
  navigatepageNums: [1],
  navigateFirstPage: 1,
  navigateLastPage: 1,
  lastPage: 1,
  firstPage: 1,
};
const taskDatail = {
  canRedeploy: true,
  taskEvaluate: null,
  auth: [
    'TASK_ADD',
    'PRODUCT_CREATE',
    'CUSTOMER_CREATE',
    'VIP_PAYMENT_ONLINE',
    'TASK_BATCH_DISPATCH',
    'CASE_ADD',
    'SERVICE_CREATE',
    'CALLCENTER_EDIT',
    'CASE_VIEW',
    'CALLCENTER_VIEW',
    'TASK_EDIT',
    'TASK_FEEDBACK',
    'VIP_INFO_NOTICE_SELECT',
    'LOGIN_PC',
    'PRODUCT_CATALOG_VIEW',
    'VIP_INFO_NOTICE_CREATE',
    'SERVICE_EDIT',
    'PORTAL_ORDER',
    'PRODUCT_EDIT',
    'VIP_SPAREPART_BACK',
    'TASK_DISPATCH',
    'TASK_POOL',
    'VIP_REPORT_VIEW',
    'TASK_VIEW',
    'AUTH_STAFF',
    'PRODUCT_CATALOG_DELETE',
    'AUTH_ROLE',
    'TASK_CLOSE',
    'TASK_BATCH_CLOSE',
    'VIP_SPAREPART_PERSION',
    'INFO_EDIT',
    'VIP_SPAREPART_INOUT',
    'TASK_AUDIT',
    'PRODUCT_VIEW',
    'CUSTOMER_DELETE',
    'CASE_DELETE',
    'INFO_VIEW',
    'EXPORT_IN',
    'VIP_APPROVE',
    'PART_EDIT',
    'SERVICE_VIEW',
    'CUSTOMER_VIEW',
    'VIP_SPAREPART_CREATE',
    'VIP_SPAREPART_VIEW',
    'CUSTOMER_PQRCODE',
    'TASK_DELETE',
    'VIP_TASK_PLAN',
    'CALLCENTER_STATISTICS',
    'PRODUCT_DELETE',
    'PRODUCT_CATALOG_CREATE',
    'CASE_EDIT',
    'VIP_INFO_CREATE',
    'SYSTEM_SEETING',
    'LOGIN_YD',
    'VIP_SPAREPART_EDIT',
    'PART_VIEW',
    'AUTH_TAG',
    'VIP_SPAREPART_STOCK',
    'PRODUCT_CATALOG_EDIT',
    'TASK_BATCH_AUDIT',
    'CUSTOMER_EDIT',
  ],
  canSeeCus: true,
  canRollBack: true,
  restructAllot: true,
  evaluateConfig: {
    modifyEvaluate: true,
    modifyEventEvaluate: true,
    autoCloseTask: true,
    useStarEvaluate: true,
    useTagEvaluate: true,
    starEvaluateNotNull: false,
    starEvaluateFeilds: [
      'starEvaluate1',
      'starEvaluate2',
      'starEvaluate3',
      'starEvaluate4',
      'starEvaluate5',
      'starEvaluate6',
    ],
    starEvaluates: [
      '服务态度',
      '服务效率',
      '响应速度',
      '工程师技能',
      '技师熟练度',
    ],
    tagEvaluates: ['速度快', '很热情', '质量高', '技术强', '有点差', '态度好'],
    reviewViewAuthiroty: 'hasTaskViewAuthiroty',
  },
  paymentConfig: {
    version: 1,
    onlineAlipay: true,
    customPayTypeEnabled: true,
    customPayType: ['月结', '周结', '现结'],
    alipayAccount: '17328571652',
  },
  canOffTask: true,
  isSparepart2: true,
  taskType: {
    id: '64593cf2-873c-4af6-b750-fb37c417ff1f',
    name: '验证宿迁正源',
    enabled: 0,
    flowSetting: {
      create: { state: true, overTime: 0, approvers: [] },
      allot: { state: true, overTime: 0, approvers: [], leader: 'none' },
      accept: { state: true, overTime: 0, approvers: [] },
      start: { state: true, overTime: 0, approvers: [], leader: 'none' },
      finish: { state: true, overTime: 0, approvers: [], leader: 'none' },
      cost: { state: true, overTime: 0, approvers: [], leader: 'none' },
      review: { state: false, overTime: 0, approvers: [], leader: 'none' },
      autoReview: { state: false, overTime: 0, approvers: [] },
      close: { state: true, overTime: 0, approvers: [], leader: 'none' },
      off: { state: true, overTime: 0, approvers: [], leader: 'none' },
    },
    createTime: 1609206940000,
    isDelete: 0,
    cardSetting: {},
    overTimeSetting: { isAhead: 1, minutes: 15, reminders: [] },
    allowPause: 1,
    pauseApprovers: [],
    options: {
      showAttachment: true,
      showSparepart: true,
      showService: true,
      customerSign: true,
      showDiscountCost: true,
      serviceReport: true,
      srSysTemplate: true,
      printTask: true,
      ptSysTemplate: true,
      editUnitPrice: false,
      receiptAttNotNull: false,
      sparepartNotNull: false,
      serviceNotNull: false,
      receiptSignNotNull: false,
    },
    reportSetting: {
      tenantFields: ['name', 'phone', 'email', 'address', 'portal'],
      customerFields: ['name', 'product', 'address', 'linkman'],
      taskFields: ['taskNo', 'planTime', 'executor'],
      receiptFields: ['sparepart', 'service', 'autograph'],
      templates: null,
    },
    printSetting: {},
    planRemindSetting: { state: true, minutes: 15 },
    delayBack: 'true',
    delayBackMin: 5,
    isLeader: '2',
    noticeLeader: null,
    noticeUsers: [],
    tags: [],
    labels: [],
    professions: [],
    description: null,
    orderId: 30,
    guideProfessions: [],
    isGuideData: false,
    config: {
      positionExceptionConfig: {
        attUploadLimitMobile: false,
        positionExceptionFlag: false,
        exceptionRange: 0,
        exceptionFlagFlows: ['start', 'finish'],
        photoWatermark: false,
        watermarkContent: ['name', 'time', 'position'],
        watermarkPosition: 'topLeft',
      },
      autographMaxCount: 3,
      color: 'rgb(115, 127, 124)',
      formUser: null,
      taskTimeState: 1,
    },
    guideData: false,
  },
  loginUser: {
    head:
      'https://static-legacy.dingtalk.com/media/lADPDgQ9qem3pdjNBCzNBCo_1066_1068.jpg',
    displayName: '黄宝成',
    roles: ['1', '2'],
    tagIds: [
      '071f50ad-c03d-11e9-bf0c-506b4b2bb4ae',
      '2d2ffb51-ba6c-11e9-bf0c-506b4b2bb4ae',
      '8a3c7f22-e804-11ea-8753-b8599f0536e4',
    ],
    userId: 'b8a4dc27-d82f-11e8-8abd-7cd30abca02e',
    staffId: '116759226639811031',
    authorities: {
      TASK_ADD: 3,
      PRODUCT_CREATE: 3,
      CUSTOMER_CREATE: 3,
      VIP_PAYMENT_ONLINE: 3,
      TASK_BATCH_DISPATCH: 3,
      CASE_ADD: 3,
      SERVICE_CREATE: 3,
      CALLCENTER_EDIT: 3,
      CASE_VIEW: 3,
      CALLCENTER_VIEW: 3,
      TASK_EDIT: 3,
      TASK_FEEDBACK: 3,
      VIP_INFO_NOTICE_SELECT: 3,
      LOGIN_PC: 3,
      PRODUCT_CATALOG_VIEW: 3,
      VIP_INFO_NOTICE_CREATE: 3,
      SERVICE_EDIT: 3,
      PORTAL_ORDER: 3,
      PRODUCT_EDIT: 3,
      VIP_SPAREPART_BACK: 3,
      TASK_DISPATCH: 3,
      TASK_POOL: 3,
      VIP_REPORT_VIEW: 3,
      TASK_VIEW: 3,
      AUTH_STAFF: 3,
      PRODUCT_CATALOG_DELETE: 3,
      AUTH_ROLE: 3,
      TASK_CLOSE: 3,
      TASK_BATCH_CLOSE: 3,
      VIP_SPAREPART_PERSION: 3,
      INFO_EDIT: 3,
      VIP_SPAREPART_INOUT: 3,
      TASK_AUDIT: 3,
      PRODUCT_VIEW: 3,
      CUSTOMER_DELETE: 3,
      CASE_DELETE: 3,
      INFO_VIEW: 3,
      EXPORT_IN: 3,
      VIP_APPROVE: 3,
      PART_EDIT: 3,
      SERVICE_VIEW: 3,
      CUSTOMER_VIEW: 3,
      VIP_SPAREPART_CREATE: 3,
      VIP_SPAREPART_VIEW: 3,
      CUSTOMER_PQRCODE: 3,
      TASK_DELETE: 3,
      VIP_TASK_PLAN: 3,
      CALLCENTER_STATISTICS: 3,
      PRODUCT_DELETE: 3,
      PRODUCT_CATALOG_CREATE: 3,
      CASE_EDIT: 3,
      VIP_INFO_CREATE: 3,
      SYSTEM_SEETING: 3,
      LOGIN_YD: 3,
      VIP_SPAREPART_EDIT: 3,
      PART_VIEW: 3,
      AUTH_TAG: 3,
      VIP_SPAREPART_STOCK: 3,
      PRODUCT_CATALOG_EDIT: 3,
      TASK_BATCH_AUDIT: 3,
      CUSTOMER_EDIT: 3,
    },
    tagIdsWithChildTag: [
      '071f50ad-c03d-11e9-bf0c-506b4b2bb4ae',
      '2d2ffb51-ba6c-11e9-bf0c-506b4b2bb4ae',
      '8a3c7f22-e804-11ea-8753-b8599f0536e4',
    ],
  },
  canCopyTask: false,
  canApprove: false,
  sparepartPrecision: 2,
  canEditTask: true,
  taskConfig: {
    taskPoolEncryptionConfig: {
      open: 0,
      taskTypeEncryptionList: [
        {
          taskTypeId: '3d67eb1e-2e1c-42ec-9ffe-291a786bba16',
          taskTypeName: null,
          taskTypeEncrypt: true,
          encrptionFilesName: null,
          encrptionFiles: [
            {
              fieldName: 'field_cawajlrWiAKFWuzy',
              displayName: '红线里被软禁的红红线里被软禁的红红线里被',
              isSystem: 0,
              isTick: 1,
              typeName: null,
            },
            {
              fieldName: 'field_ZkjlI97ixCgBitpa',
              displayName: '红线里被软禁的红红线里被软禁的红红线里被',
              isSystem: 0,
              isTick: 1,
              typeName: null,
            },
            {
              fieldName: 'field_mpuTznUmMRuDCBjd',
              displayName: '单行文字单行文字单行文字单行文字单行文字',
              isSystem: 0,
              isTick: 1,
              typeName: null,
            },
            {
              fieldName: 'field_ipCsD8Ra8GmyYPPG',
              displayName: '多行文本',
              isSystem: 0,
              isTick: 1,
              typeName: null,
            },
            {
              fieldName: 'field_9beIVzjVlCVDJ6tJ',
              displayName: '客户关联字段',
              isSystem: 0,
              isTick: 1,
              typeName: null,
            },
            {
              fieldName: 'field_ZbWKfHoZyF72zsns',
              displayName: '扫码',
              isSystem: 0,
              isTick: 0,
              typeName: null,
            },
            {
              fieldName: 'field_P7PCFbHFXjLUSYqg',
              displayName: '标题',
              isSystem: 0,
              isTick: 0,
              typeName: null,
            },
            {
              fieldName: 'field_HOSrwy1lMrNAKIef',
              displayName: '多级',
              isSystem: 0,
              isTick: 0,
              typeName: null,
            },
            {
              fieldName: 'field_9glBa0yG2c6HZiZv',
              displayName: '数字',
              isSystem: 0,
              isTick: 0,
              typeName: null,
            },
            {
              fieldName: 'taskType',
              displayName: '工单类型',
              isSystem: 1,
              isTick: 1,
              typeName: 'taskTypeEncrypt',
            },
            {
              fieldName: 'taskNo',
              displayName: '工单编号',
              isSystem: 1,
              isTick: 1,
              typeName: null,
            },
            {
              fieldName: 'customer',
              displayName: '联系人',
              isSystem: 1,
              isTick: 1,
              typeName: 'tlmName',
            },
            {
              fieldName: 'customer',
              displayName: '地址',
              isSystem: 1,
              isTick: 1,
              typeName: 'taddress',
            },
            {
              fieldName: 'customer',
              displayName: '产品',
              isSystem: 1,
              isTick: 1,
              typeName: 'products',
            },
            {
              fieldName: 'customer',
              displayName: '客户',
              isSystem: 1,
              isTick: 1,
              typeName: 'customerName',
            },
            {
              fieldName: 'planTime',
              displayName: '计划时间',
              isSystem: 1,
              isTick: 1,
              typeName: null,
            },
            {
              fieldName: 'description',
              displayName: '描述',
              isSystem: 1,
              isTick: 0,
              typeName: null,
            },
          ],
        },
        {
          taskTypeId: '951ed181-b58d-4c01-a62c-052a29016b9b',
          taskTypeName: null,
          taskTypeEncrypt: true,
          encrptionFilesName: null,
          encrptionFiles: [
            {
              fieldName: 'field_75Om75DUPtojimji',
              displayName: '标题',
              isSystem: 0,
              isTick: 1,
              typeName: null,
            },
            {
              fieldName: 'field_qfWecljChvKMWHt0',
              displayName: '照片',
              isSystem: 0,
              isTick: 1,
              typeName: null,
            },
            {
              fieldName: 'field_NzX6e0fZVdR8iwni',
              displayName: '111',
              isSystem: 0,
              isTick: 0,
              typeName: null,
            },
            {
              fieldName: 'field_jRIxj1LZ0clYPtge',
              displayName: '地址',
              isSystem: 0,
              isTick: 1,
              typeName: null,
            },
            {
              fieldName: 'field_qHVY21jX2tpR8aZA',
              displayName: '扫码',
              isSystem: 0,
              isTick: 0,
              typeName: null,
            },
            {
              fieldName: 'field_LQu2h2OOWJVspu76',
              displayName: '下拉菜单',
              isSystem: 0,
              isTick: 0,
              typeName: null,
            },
            {
              fieldName: 'field_dc149yIKsVKIck5A',
              displayName: '多级菜单',
              isSystem: 0,
              isTick: 0,
              typeName: null,
            },
            {
              fieldName: 'field_Nbg0FeyRHh6Mgfex',
              displayName: '数字',
              isSystem: 0,
              isTick: 0,
              typeName: null,
            },
            {
              fieldName: 'field_fmuKEoTMO6Y90wbO',
              displayName: '电话',
              isSystem: 0,
              isTick: 0,
              typeName: null,
            },
            {
              fieldName: 'field_pi428V9qb5NsgaVf',
              displayName: '',
              isSystem: 0,
              isTick: 0,
              typeName: null,
            },
            {
              fieldName: 'field_DwS2mT4Kll23nYGz',
              displayName: '日期',
              isSystem: 0,
              isTick: 0,
              typeName: null,
            },
            {
              fieldName: 'field_F0MNtULvaBA1LxzL',
              displayName: '客户关联字段',
              isSystem: 0,
              isTick: 0,
              typeName: null,
            },
            {
              fieldName: 'field_NNpBCQ3RGU2Tosux',
              displayName: '人员',
              isSystem: 0,
              isTick: 0,
              typeName: null,
            },
            {
              fieldName: 'taskType',
              displayName: '工单类型',
              isSystem: 1,
              isTick: 1,
              typeName: 'taskTypeEncrypt',
            },
            {
              fieldName: 'taskNo',
              displayName: '工单编号',
              isSystem: 1,
              isTick: 1,
              typeName: null,
            },
            {
              fieldName: 'customer',
              displayName: '联系人',
              isSystem: 1,
              isTick: 1,
              typeName: 'tlmName',
            },
            {
              fieldName: 'customer',
              displayName: '地址',
              isSystem: 1,
              isTick: 1,
              typeName: 'taddress',
            },
            {
              fieldName: 'customer',
              displayName: '产品',
              isSystem: 1,
              isTick: 1,
              typeName: 'products',
            },
            {
              fieldName: 'customer',
              displayName: '客户',
              isSystem: 1,
              isTick: 1,
              typeName: 'customerName',
            },
            {
              fieldName: 'planTime',
              displayName: '计划时间',
              isSystem: 1,
              isTick: 1,
              typeName: null,
            },
          ],
        },
        {
          taskTypeId: '4ea31962-d0b7-4317-96dd-601ee6993a06',
          taskTypeName: null,
          taskTypeEncrypt: false,
          encrptionFilesName: null,
          encrptionFiles: [
            {
              fieldName: 'level',
              displayName: '优先级',
              isSystem: 1,
              isTick: 0,
              typeName: null,
            },
          ],
        },
        {
          taskTypeId: 'a191b13c-576d-4c13-9ab8-f5b2c3ce2315',
          taskTypeName: null,
          taskTypeEncrypt: false,
          encrptionFilesName: null,
          encrptionFiles: [],
        },
        {
          taskTypeId: '1',
          taskTypeName: null,
          taskTypeEncrypt: false,
          encrptionFilesName: null,
          encrptionFiles: [],
        },
        {
          taskTypeId: '3329be8f-687b-4428-9b59-699d4a1e493b',
          taskTypeName: null,
          taskTypeEncrypt: true,
          encrptionFilesName: null,
          encrptionFiles: [
            {
              fieldName: 'taskType',
              displayName: '工单类型',
              isSystem: 1,
              isTick: 0,
              typeName: 'taskTypeEncrypt',
            },
            {
              fieldName: 'taskNo',
              displayName: '工单编号',
              isSystem: 1,
              isTick: 0,
              typeName: null,
            },
          ],
        },
      ],
      systemEncryptionList: null,
      extEncyptionList: null,
    },
    taskCustomerConfig: {
      showAddress: true,
      showLinkman: true,
      showProduct: true,
      enable: true,
      orderId: 0,
    },
    taskPlantimeConfig: { orderId: 2, enable: true },
    taskAttachmentConfig: { orderId: 4, enable: true },
    taskDescriptionConfig: { orderId: 3, enable: true },
    taskClassificationConfig: { orderId: 1, enable: true },
    taskBalanceConfig: {
      openUserDefinedBalance: true,
      balanceViewAuthiroty: 'onlyHasBalanceAuthiroty',
    },
    taskUpdateConfig: ['closed', 'costed'],
    level: ['一般', '紧急', '非常紧急'],
    type: ['安装', '维修', '培训'],
    taskCreate: true,
    taskAllot: true,
    taskStart: true,
    taskAccept: true,
    taskFinish: true,
    taskRefuse: true,
    taskCost: true,
    taskClose: true,
    taskOff: true,
    taskReview: false,
    taskReallot: false,
    taskPlanTime: true,
    taskSynergy: true,
    taskRollBack: true,
    taskAllotByMap: true,
    taskPoolOn: true,
    allotByTag: true,
    allotByExclusiveTag: true,
    canBalanceBatch: false,
    canCloseBatch: false,
    autoReview: true,
    responseWithUrl: true,
    autoDispatch: true,
    poolMaxRange: 10000,
    poolMaxUsers: 5,
    poolOverTime: 1,
    allowAutoDispatch: true,
    planTimeNotice: 0,
    poolByTag: true,
    reallotToPool: true,
    allowExec2Edit: true,
    maxTaskTypeNum: 20,
    approveRemark: true,
    reallotStateRetain: false,
    invisibleLocation: true,
    mobileShowTaskInfo: true,
    mobileShowRevenueInfo: true,
    reallotRemarkNotNull: true,
    singleDayMaxOrderNum: 50,
    mobileRemarkLocation: true,
    appOperateButton: true,
    needApprove: false,
    notice: true,
  },
  canPause: true,
  receiptTaskForUpdate: {
    id: '09050301-5eb1-11eb-8753-b8599f0536e4',
    taskNo: 'TRR20321010001',
    name: null,
    customer: {
      createUser: 'e993e9de-8f62-11ea-97fd-7cd30abca02e',
      updateUser: null,
      createTime: null,
      updateTime: null,
      id: '901fe9ec-48e5-11eb-8753-b8599f0536e4',
      name: 's饭撒发的',
      enName: null,
      serialNumber: 'nndaf123123',
      status: null,
      level: null,
      superior: null,
      teamId: null,
      customerManager: '',
      customerManagerName: '',
      remark: null,
      industry: null,
      type: null,
      taskCount: null,
      productCount: null,
      isDelete: null,
      attribute: {},
      companyNature: null,
      tagIds: null,
      tags: [
        { id: 'a532181d-ac51-11e9-8123-7cd30abca02e', tagName: '孙冲团队' },
      ],
      createUserId: null,
      createLoginUser: null,
      lmName: 's饭撒发的',
      lmPhone: '123151',
      lmEmail: null,
      customerAddress: {
        adCountry: '',
        adDist: '市北区',
        adProvince: '山东省',
        adCity: '青岛市',
        adAddress: '',
        adLongitude: 120.374731,
        adLatitude: 36.087609,
        addressType: 0,
        validAddress: true,
      },
      source: null,
      guideProfessions: [],
      isGuideData: false,
      products: [],
      guideData: false,
      focus: false,
    },
    type: null,
    level: '中',
    serviceType: '保内免费',
    serviceContent: '安装',
    description: null,
    state: 'allocated',
    createTime: 1611540002000,
    executorId: null,
    executor: {
      userId: 'b47a92d3-5640-11eb-9e6c-7cd30aeb7fca',
      loginName: null,
      displayName: '001',
      email: null,
      cellPhone: null,
      lastLoginTime: null,
      enabled: 1,
      weixinid: null,
      powercode: null,
      head: '',
      sex: null,
      firstLogin: 0,
      tagList: [],
      departments: null,
      roles: null,
      attribute: {},
      openid: '$:LWCP_v1:$/MuigDv7l1kSyDE5OtP3XIHYY62p0UWN',
      longitude: null,
      latitude: null,
      isDelete: null,
      synOpenid: null,
      staffId: '294351613747665',
      tenantId: null,
      mainTeamId: null,
      unfinishedTask: null,
      todayFinishedTask: null,
      state: null,
      cusDistance: null,
      wechat: null,
      superAdmin: null,
      isTeamLeader: 0,
    },
    synergies: [],
    attribute: { otherNotifier_pool: null },
    balanceAttribute: {},
    createUserId: '61765593-e90d-11ea-a482-7cd30aeb7fca',
    createUser: {
      userId: '61765593-e90d-11ea-a482-7cd30aeb7fca',
      loginName: null,
      displayName: '无距',
      email: null,
      cellPhone: null,
      lastLoginTime: null,
      enabled: 1,
      weixinid: null,
      powercode: null,
      head:
        'https://static-legacy.dingtalk.com/media/lADPGo_k8hksbW_NAZbNAZU_405_406.jpg',
      sex: null,
      firstLogin: 0,
      tagList: [],
      departments: null,
      roles: null,
      attribute: {},
      openid: '$:LWCP_v1:$aPuhuBS4+TcV4xxsn+voFw==',
      longitude: null,
      latitude: null,
      isDelete: null,
      synOpenid: null,
      staffId: '0725031605844797',
      tenantId: null,
      mainTeamId: null,
      unfinishedTask: null,
      todayFinishedTask: null,
      state: null,
      cusDistance: null,
      wechat: null,
      superAdmin: null,
      isTeamLeader: 0,
    },
    attachment: [],
    isEncryptAttachment: false,
    planTime: '2021-01-26 10:00:00',
    isEncryptPlanTime: false,
    isReview: 0,
    degree: null,
    suggestion: null,
    balanceConfirm: 0,
    balanceTime: null,
    balanceUserId: null,
    balanceUser: null,
    remark: [],
    receiptContent: null,
    product: null,
    productId: null,
    completeTime: null,
    startTime: null,
    startOn: 1,
    autograph: null,
    autographUrl: null,
    reviewTime: null,
    reviewUserId: null,
    reviewUser: null,
    tenantId: '7416b42a-25cc-11e7-a500-00163e12f748',
    allotTime: 1611543601000,
    allotUserId: '61765593-e90d-11ea-a482-7cd30aeb7fca',
    allotUser: {
      userId: '61765593-e90d-11ea-a482-7cd30aeb7fca',
      loginName: null,
      displayName: '无距',
      email: null,
      cellPhone: null,
      lastLoginTime: null,
      enabled: 1,
      weixinid: null,
      powercode: null,
      head:
        'https://static-legacy.dingtalk.com/media/lADPGo_k8hksbW_NAZbNAZU_405_406.jpg',
      sex: null,
      firstLogin: 0,
      tagList: [],
      departments: null,
      roles: null,
      attribute: {},
      openid: null,
      longitude: null,
      latitude: null,
      isDelete: null,
      synOpenid: null,
      staffId: '0725031605844797',
      tenantId: null,
      mainTeamId: null,
      unfinishedTask: null,
      todayFinishedTask: null,
      state: null,
      cusDistance: null,
      wechat: null,
      superAdmin: null,
      isTeamLeader: 0,
    },
    acceptTime: null,
    closeTime: null,
    taddress: {
      id: '90249812-48e5-11eb-9e6c-7cd30aeb7fca',
      city: '青岛市',
      dist: '市北区',
      address: '',
      latitude: 36.087609,
      province: '山东省',
      longitude: 120.374731,
    },
    isEncryptTaddress: false,
    tlmId: '9025b5ad-48e5-11eb-9e6c-7cd30aeb7fca',
    tlmName: 's饭撒发的',
    tlmPhone: '123151',
    tversion: 'v2',
    inTaskPool: 1,
    updateTime: 1611543600000,
    products: [
      {
        id: 'dff89285-48e7-11eb-9e6c-7cd30aeb7fca',
        name: '发达发发',
        type: '',
        serialNumber: '',
      },
    ],
    evaluate: null,
    evaluateContent: null,
    evaluateSource: null,
    profit: null,
    sale: null,
    cost: null,
    templateId: '64593cf2-873c-4af6-b750-fb37c417ff1f',
    templateName: '验证宿迁正源',
    cardInfo: [],
    inApprove: 0,
    isPaused: 0,
    overTime: null,
    isOverTime: 0,
    taskUsedTime: null,
    taskUsedTimeStr: '',
    acceptUsedTime: null,
    acceptUsedTimeStr: '',
    workUsedTime: null,
    workUsedTimeStr: '',
    onceOverTime: 1,
    taskResponseTime: null,
    taskResponseTimeStr: '',
    expenseDetail: null,
    isDelete: 0,
    settlement: null,
    sparepart: null,
    onceRefused: 0,
    oncePaused: 0,
    allotType: 3,
    allotTypeStr: '自动派单',
    onceReallot: 0,
    positionException: 0,
    oncePrinted: 0,
    onceRollback: 0,
    validAddress: true,
    expenseSheet: null,
    evaluateObj: null,
    source: '计划任务创建',
    eventId: null,
    eventNo: null,
    guideProfessions: [],
    isGuideData: false,
    isSettled: -1,
    isReviewed: -1,
    isEvaluated: -1,
    isClosed: -1,
    tick: null,
    guideData: false,
    taddressStr: '山东省,青岛市,市北区',
    v2: true,
  },
  remarkList: [
    {
      createUser: null,
      updateUser: null,
      createTime: '2018-10-01 00:50:39',
      updateTime: null,
      id: 12,
      content: '&lt;&gt;&quot;#$%^&amp;*()\nfdjasl;fdjaslfd\n呵呵。',
      module: 'task',
      creatorId: 'bd06f0e4-7f75-11e8-8abd-7cd30abca02e',
      creatorName: '殷海峰',
      sequence: 2,
    },
    {
      createUser: null,
      updateUser: null,
      createTime: '2018-10-01 00:50:50',
      updateTime: null,
      id: 13,
      content: '工单备注11111111111AAAAAAAAAAAAAAAAAA',
      module: 'task',
      creatorId: 'bd06f0e4-7f75-11e8-8abd-7cd30abca02e',
      creatorName: '殷海峰',
      sequence: 3,
    },
    {
      createUser: null,
      updateUser: null,
      createTime: '2018-10-01 00:52:12',
      updateTime: null,
      id: 15,
      content: '工单备注222222',
      module: 'task',
      creatorId: 'bd06f0e4-7f75-11e8-8abd-7cd30abca02e',
      creatorName: '殷海峰',
      sequence: 4,
    },
    {
      createUser: null,
      updateUser: null,
      createTime: '2018-10-19 00:20:56',
      updateTime: null,
      id: 1120,
      content: '工单备注2',
      module: 'task',
      creatorId: 'bd06f0e4-7f75-11e8-8abd-7cd30abca02e',
      creatorName: '殷海峰',
      sequence: 5,
    },
    {
      createUser: null,
      updateUser: null,
      createTime: '2018-10-01 00:52:49',
      updateTime: null,
      id: 16,
      content: '工单备注33333',
      module: 'task',
      creatorId: 'bd06f0e4-7f75-11e8-8abd-7cd30abca02e',
      creatorName: '殷海峰',
      sequence: 6,
    },
    {
      createUser: null,
      updateUser: null,
      createTime: '2018-10-09 11:06:42',
      updateTime: null,
      id: 459,
      content: '&lt;&gt;&amp;&quot;',
      module: 'task',
      creatorId: 'bd06f0e4-7f75-11e8-8abd-7cd30abca02e',
      creatorName: '殷海峰',
      sequence: 7,
    },
    {
      createUser: null,
      updateUser: null,
      createTime: '2018-10-19 00:20:43',
      updateTime: null,
      id: 1119,
      content: '<>&"',
      module: 'task',
      creatorId: 'bd06f0e4-7f75-11e8-8abd-7cd30abca02e',
      creatorName: '殷海峰',
      sequence: 8,
    },
    {
      createUser: null,
      updateUser: null,
      createTime: '2020-04-14 11:51:52',
      updateTime: null,
      id: 24116,
      content: '陶然测试，看显示什么',
      module: 'task',
      creatorId: '8adc6630-380e-11ea-a544-506b4b2bb4ae',
      creatorName: '王文娟',
      sequence: 9,
    },
    {
      createUser: null,
      updateUser: null,
      createTime: '2020-12-02 10:52:09',
      updateTime: null,
      id: 33172,
      content: '乐天备注模板',
      module: 'task',
      creatorId: '0b10a2df-308e-11eb-9e6c-7cd30aeb7fca',
      creatorName: '乐天',
      sequence: 10,
    },
  ],
  isPay: false,
  variationConfig: {
    maxCardField: 10,
    maxTaskCardRow: 60,
    maxEventCardRow: 60,
    maxTaskCardNum: 20,
    maxEventCardNum: 20,
    taskFieldNum: 500,
    customerFieldNum: 100,
    productFieldNum: 100,
    eventFieldNum: 100,
    extraFileStorage: 10,
    planTaskLimit: 1000,
    taskLimit: 800000,
    eventLimit: 800000,
    sparepartLimit: 10000,
    serviceLimit: 10000,
    customerLimit: 100000,
    productLimit: 100000,
    productTemplateLimit: 1000,
    productCodeLimit: 30000,
    tagLimit: 100,
    roleLimit: 100,
    wikiLimit: 10000,
    noticeLimit: 10000,
    repertoryLimit: 100,
    singleRepertoryCategoryLimit: 10000,
    personalSparepartLimit: 10000,
    singleLinkmanLimit: 500,
    singleAddressLimit: 500,
    singleProductLimit: 500,
    singleChooseUserLimit: 100,
  },
  cardInfo: [],
  receiptTaskForRead: null,
  active: null,
  isAllowUpdate: true,
  receiptExpenseSheetForUpdate: null,
  unFinishedAppr: null,
  receiptExpenseSheetForRead: null,
  messageConfig: {
    ddTaskCreate: true,
    ddTaskTransfer: true,
    ddTaskResponse: true,
    ddTaskFinish: true,
    smsTaskResponse: false,
    smsTaskFinish: false,
    smsEventAllot: false,
    smsEventFinish: false,
    ddTaskStart: true,
    ddTaskUpdate: true,
    ddTaskRollBack: true,
    ddTaskOff: true,
    ddEventCreate: true,
    ddEventUpdate: true,
    ddEventRollBack: true,
    ddEventEvaluate: true,
    ddEventOff: true,
    ddTaskEvaluate: true,
    ddTaskClose: true,
    ddTaskCost: true,
    taskRemark: true,
    taskRemarkInited: true,
    eventRemark: true,
    eventRemarkInited: true,
    reportSendTime: '09:00:00',
    toBeDoneTipsSwitch: true,
    taskResponseTaskTypeList: [],
    taskFinishTaskTypeList: [],
    eventAllotEventTypeList: [],
    eventFinishEventTypeList: [],
    taskPlanTimeTaskTypeList: [],
  },
  task: {
    id: '09050301-5eb1-11eb-8753-b8599f0536e4',
    taskNo: 'TRR20321010001',
    name: null,
    customer: {
      createUser: 'e993e9de-8f62-11ea-97fd-7cd30abca02e',
      updateUser: null,
      createTime: null,
      updateTime: null,
      id: '901fe9ec-48e5-11eb-8753-b8599f0536e4',
      name: 's饭撒发的',
      enName: null,
      serialNumber: 'nndaf123123',
      status: null,
      level: null,
      superior: null,
      teamId: null,
      customerManager: '',
      customerManagerName: '',
      remark: null,
      industry: null,
      type: null,
      taskCount: null,
      productCount: null,
      isDelete: null,
      attribute: {},
      companyNature: null,
      tagIds: null,
      tags: [
        { id: 'a532181d-ac51-11e9-8123-7cd30abca02e', tagName: '孙冲团队' },
      ],
      createUserId: null,
      createLoginUser: null,
      lmName: 's饭撒发的',
      lmPhone: '123151',
      lmEmail: null,
      customerAddress: {
        adCountry: '',
        adDist: '市北区',
        adProvince: '山东省',
        adCity: '青岛市',
        adAddress: '',
        adLongitude: 120.374731,
        adLatitude: 36.087609,
        addressType: 0,
        validAddress: true,
      },
      source: null,
      guideProfessions: [],
      isGuideData: false,
      products: [],
      guideData: false,
      focus: false,
    },
    type: null,
    level: '中',
    serviceType: '保内免费',
    serviceContent: '安装',
    description: null,
    state: 'allocated',
    createTime: 1611540002000,
    executorId: null,
    executor: {
      userId: 'b47a92d3-5640-11eb-9e6c-7cd30aeb7fca',
      loginName: null,
      displayName: '001',
      email: null,
      cellPhone: null,
      lastLoginTime: null,
      enabled: 1,
      weixinid: null,
      powercode: null,
      head: '',
      sex: null,
      firstLogin: 0,
      tagList: [],
      departments: null,
      roles: null,
      attribute: {},
      openid: '$:LWCP_v1:$/MuigDv7l1kSyDE5OtP3XIHYY62p0UWN',
      longitude: null,
      latitude: null,
      isDelete: null,
      synOpenid: null,
      staffId: '294351613747665',
      tenantId: null,
      mainTeamId: null,
      unfinishedTask: null,
      todayFinishedTask: null,
      state: null,
      cusDistance: null,
      wechat: null,
      superAdmin: null,
      isTeamLeader: 0,
    },
    synergies: [],
    attribute: { otherNotifier_pool: null },
    balanceAttribute: {},
    createUserId: '61765593-e90d-11ea-a482-7cd30aeb7fca',
    createUser: {
      userId: '61765593-e90d-11ea-a482-7cd30aeb7fca',
      loginName: null,
      displayName: '无距',
      email: null,
      cellPhone: null,
      lastLoginTime: null,
      enabled: 1,
      weixinid: null,
      powercode: null,
      head:
        'https://static-legacy.dingtalk.com/media/lADPGo_k8hksbW_NAZbNAZU_405_406.jpg',
      sex: null,
      firstLogin: 0,
      tagList: [],
      departments: null,
      roles: null,
      attribute: {},
      openid: '$:LWCP_v1:$aPuhuBS4+TcV4xxsn+voFw==',
      longitude: null,
      latitude: null,
      isDelete: null,
      synOpenid: null,
      staffId: '0725031605844797',
      tenantId: null,
      mainTeamId: null,
      unfinishedTask: null,
      todayFinishedTask: null,
      state: null,
      cusDistance: null,
      wechat: null,
      superAdmin: null,
      isTeamLeader: 0,
    },
    attachment: [],
    isEncryptAttachment: false,
    planTime: '2021-01-26 10:00:00',
    isEncryptPlanTime: false,
    isReview: 0,
    degree: null,
    suggestion: null,
    balanceConfirm: 0,
    balanceTime: null,
    balanceUserId: null,
    balanceUser: null,
    remark: [],
    receiptContent: null,
    product: null,
    productId: null,
    completeTime: null,
    startTime: null,
    startOn: 1,
    autograph: null,
    autographUrl: null,
    reviewTime: null,
    reviewUserId: null,
    reviewUser: null,
    tenantId: '7416b42a-25cc-11e7-a500-00163e12f748',
    allotTime: 1611543601000,
    allotUserId: '61765593-e90d-11ea-a482-7cd30aeb7fca',
    allotUser: {
      userId: '61765593-e90d-11ea-a482-7cd30aeb7fca',
      loginName: null,
      displayName: '无距',
      email: null,
      cellPhone: null,
      lastLoginTime: null,
      enabled: 1,
      weixinid: null,
      powercode: null,
      head:
        'https://static-legacy.dingtalk.com/media/lADPGo_k8hksbW_NAZbNAZU_405_406.jpg',
      sex: null,
      firstLogin: 0,
      tagList: [],
      departments: null,
      roles: null,
      attribute: {},
      openid: null,
      longitude: null,
      latitude: null,
      isDelete: null,
      synOpenid: null,
      staffId: '0725031605844797',
      tenantId: null,
      mainTeamId: null,
      unfinishedTask: null,
      todayFinishedTask: null,
      state: null,
      cusDistance: null,
      wechat: null,
      superAdmin: null,
      isTeamLeader: 0,
    },
    acceptTime: null,
    closeTime: null,
    taddress: {
      id: '90249812-48e5-11eb-9e6c-7cd30aeb7fca',
      city: '青岛市',
      dist: '市北区',
      address: '',
      latitude: 36.087609,
      province: '山东省',
      longitude: 120.374731,
    },
    isEncryptTaddress: false,
    tlmId: '9025b5ad-48e5-11eb-9e6c-7cd30aeb7fca',
    tlmName: 's饭撒发的',
    tlmPhone: '123151',
    tversion: 'v2',
    inTaskPool: 1,
    updateTime: 1611543600000,
    products: [
      {
        id: 'dff89285-48e7-11eb-9e6c-7cd30aeb7fca',
        name: '发达发发',
        type: '',
        serialNumber: '',
      },
    ],
    evaluate: null,
    evaluateContent: null,
    evaluateSource: null,
    profit: null,
    sale: null,
    cost: null,
    templateId: '64593cf2-873c-4af6-b750-fb37c417ff1f',
    templateName: '验证宿迁正源',
    cardInfo: [],
    inApprove: 0,
    isPaused: 0,
    overTime: null,
    isOverTime: 0,
    taskUsedTime: null,
    taskUsedTimeStr: '',
    acceptUsedTime: null,
    acceptUsedTimeStr: '',
    workUsedTime: null,
    workUsedTimeStr: '',
    onceOverTime: 1,
    taskResponseTime: null,
    taskResponseTimeStr: '',
    expenseDetail: null,
    isDelete: 0,
    settlement: null,
    sparepart: null,
    onceRefused: 0,
    oncePaused: 0,
    allotType: 3,
    allotTypeStr: '自动派单',
    onceReallot: 0,
    positionException: 0,
    oncePrinted: 0,
    onceRollback: 0,
    validAddress: true,
    expenseSheet: null,
    evaluateObj: null,
    source: '计划任务创建',
    eventId: null,
    eventNo: null,
    guideProfessions: [],
    isGuideData: false,
    isSettled: -1,
    isReviewed: -1,
    isEvaluated: -1,
    isClosed: -1,
    tick: null,
    guideData: false,
    taddressStr: '山东省,青岛市,市北区',
    v2: true,
  },
  canViewTask: true,
  isRepertoryDiff: false,
  balanceFieldInfos: [
    {
      fieldId: '300001',
      tableName: 'balance',
      isSystem: 1,
      fieldName: 'remark',
      displayName: '系统预设，用于占位',
      formType: 'text',
      defaultValue: null,
      maxLength: 0,
      dotLength: 0,
      isNull: 1,
      isValidate: 0,
      enabled: false,
      isSearch: 0,
      isAdd: 1,
      isReadonly: 0,
      placeHolder: '',
      setting: {},
      orderId: 0,
      tableChsName: null,
    },
    {
      fieldId: '300002',
      tableName: 'balance',
      isSystem: 0,
      fieldName: 'field_Ah58JgBl',
      displayName: '结算周期',
      formType: 'text',
      defaultValue: null,
      maxLength: 0,
      dotLength: 0,
      isNull: 1,
      isValidate: 0,
      enabled: false,
      isSearch: 0,
      isAdd: 1,
      isReadonly: 0,
      placeHolder: '请填写结算周期',
      setting: { isOpen: true },
      orderId: 0,
      tableChsName: null,
    },
    {
      fieldId: '300003',
      tableName: 'balance',
      isSystem: 0,
      fieldName: 'field_YQvepfuW',
      displayName: '结算方式',
      formType: 'select',
      defaultValue: null,
      maxLength: 0,
      dotLength: 0,
      isNull: 1,
      isValidate: 0,
      enabled: false,
      isSearch: 0,
      isAdd: 1,
      isReadonly: 0,
      placeHolder: '请选择结算方法',
      setting: { dataSource: ['对公', '个人', '其他', '挂账'], isOpen: true },
      orderId: 1,
      tableChsName: null,
    },
    {
      fieldId: '300004',
      tableName: 'balance',
      isSystem: 0,
      fieldName: 'field_wStqgzAR',
      displayName: '结算金额',
      formType: 'text',
      defaultValue: null,
      maxLength: 0,
      dotLength: 0,
      isNull: 1,
      isValidate: 0,
      enabled: false,
      isSearch: 0,
      isAdd: 1,
      isReadonly: 0,
      placeHolder: '请填写结算金额',
      setting: { dataSource: ['对公', '个人', '其他'], isOpen: true },
      orderId: 2,
      tableChsName: null,
    },
    {
      fieldId: '300005',
      tableName: 'balance',
      isSystem: 0,
      fieldName: 'field_jRCTtBeN',
      displayName: '结算类别',
      formType: 'select',
      defaultValue: null,
      maxLength: 0,
      dotLength: 0,
      isNull: 1,
      isValidate: 0,
      enabled: false,
      isSearch: 0,
      isAdd: 1,
      isReadonly: 0,
      placeHolder: '请选择结算类别',
      setting: {
        dataSource: [
          '基本户',
          '一般户',
          '支付宝',
          '浦发银行',
          '建设银行',
          '中国银行',
          '其他银行',
        ],
        isOpen: true,
      },
      orderId: 3,
      tableChsName: null,
    },
    {
      fieldId: '300006',
      tableName: 'balance',
      isSystem: 0,
      fieldName: 'field_kfA4rZQ3',
      displayName: '结算选项',
      formType: 'select',
      defaultValue: null,
      maxLength: 0,
      dotLength: 0,
      isNull: 1,
      isValidate: 0,
      enabled: false,
      isSearch: 0,
      isAdd: 1,
      isReadonly: 0,
      placeHolder: '请选择结算选项',
      setting: { dataSource: ['已结账', '未结清'], isOpen: true },
      orderId: 4,
      tableChsName: null,
    },
    {
      fieldId: '300007',
      tableName: 'balance',
      isSystem: 0,
      fieldName: 'field_rWgfb4a9',
      displayName: '备注',
      formType: 'textarea',
      defaultValue: null,
      maxLength: 0,
      dotLength: 0,
      isNull: 1,
      isValidate: 0,
      enabled: false,
      isSearch: 0,
      isAdd: 1,
      isReadonly: 0,
      placeHolder: '请填写备注',
      setting: { dataSource: '', isOpen: true },
      orderId: 5,
      tableChsName: null,
    },
    {
      fieldId: '300008',
      tableName: 'balance',
      isSystem: 0,
      fieldName: 'field_0Y5MDZ3G',
      displayName: '附件',
      formType: 'attachment',
      defaultValue: null,
      maxLength: 0,
      dotLength: 0,
      isNull: 1,
      isValidate: 0,
      enabled: false,
      isSearch: 0,
      isAdd: 1,
      isReadonly: 0,
      placeHolder: '',
      setting: { dataSource: '', isOpen: true },
      orderId: 6,
      tableChsName: null,
    },
  ],
  receiptConfig: {
    showSparepart: true,
    showService: true,
    showAttachment: true,
    customReceipt: true,
    editReceipt: true,
    showDiscountCost: true,
    serviceReport: true,
    customerSign: true,
  },
  canOffAppr: false,
  canDeleteTask: true,
};
export {
  taskValue,
  taskUrlParams,
  taskTypes,
  taskFields,
  taskState,
  taskTask,
  taskAllotFields,
  taskAllotTask,
  taskAllotLoginUser,
  taskAccountFields,
  taskfeedBackTask,
  taskfeedBackConfig,
  taskSteps,
  productFields,
  productValue,
  productSerachCustomer,
  productSearchTemplate,
  productSearchCatalog,
  taskDatail
};
