let obj = {
  'isSelfHelpEnabled': true,
  'loginUser': {
    'displayName': '薄德忠',
    'roles': ['1'],
    'tagIds': ['2aca023e-965a-11e9-bfc9-00163e304a25', 'a3dda245-e5df-11ea-9929-00163e304a25', 'bda400f6-2ae1-11ea-bfc9-00163e304a25', 'fc637ab7-e76d-11ea-9929-00163e304a25'],
    'userId': '6839d043-683e-11ea-bfc9-00163e304a25',
    'authorities': {
      'TASK_ADD': 3,
      'CALENDAR_VIEW': 3,
      'PRODUCT_CREATE': 3,
      'CUSTOMER_CREATE': 3,
      'VIP_PAYMENT_ONLINE': 3,
      'TASK_BATCH_DISPATCH': 3,
      'CASE_ADD': 3,
      'SERVICE_CREATE': 3,
      'CASE_VIEW': 3,
      'TASK_EDIT': 3,
      'TASK_FEEDBACK': 3,
      'VIP_INFO_NOTICE_SELECT': 3,
      'LOGIN_PC': 3,
      'SMS_CONFIG': 3,
      'VIP_INFO_NOTICE_CREATE': 3,
      'SERVICE_EDIT': 3,
      'PORTAL_ORDER': 3,
      'PRODUCT_EDIT': 3,
      'VIP_SPAREPART_BACK': 3,
      'TASK_DISPATCH': 3,
      'TASK_POOL': 3,
      'VIP_REPORT_VIEW': 3,
      'TASK_VIEW': 3,
      'AUTH_STAFF': 3,
      'AUTH_ROLE': 3,
      'TASK_CLOSE': 3,
      'TASK_BATCH_CLOSE': 3,
      'VIP_SPAREPART_PERSION': 3,
      'INFO_EDIT': 3,
      'VIP_SPAREPART_INOUT': 3,
      'TASK_AUDIT': 3,
      'PRODUCT_VIEW': 3,
      'CUSTOMER_DELETE': 3,
      'CASE_DELETE': 3,
      'INFO_VIEW': 3,
      'EXPORT_IN': 3,
      'VIP_APPROVE': 3,
      'PART_EDIT': 3,
      'SERVICE_VIEW': 3,
      'CUSTOMER_VIEW': 3,
      'VIP_SPAREPART_CREATE': 3,
      'VIP_SPAREPART_VIEW': 3,
      'CUSTOMER_PQRCODE': 3,
      'TASK_DELETE': 3,
      'VIP_TASK_PLAN': 3,
      'PRODUCT_DELETE': 3,
      'CASE_EDIT': 3,
      'VIP_INFO_CREATE': 3,
      'SYSTEM_SEETING': 3,
      'LOGIN_YD': 3,
      'VIP_SPAREPART_EDIT': 3,
      'PART_VIEW': 3,
      'AUTH_TAG': 3,
      'VIP_SPAREPART_STOCK': 3,
      'TASK_BATCH_AUDIT': 3,
      'CUSTOMER_EDIT': 3
    },
    'tagIdsWithChildTag': ['08e1d3bb-ed84-11ea-a442-00163e304a25', '2aca023e-965a-11e9-bfc9-00163e304a25', 'a3dda245-e5df-11ea-9929-00163e304a25', 'bda400f6-2ae1-11ea-bfc9-00163e304a25', 'fc637ab7-e76d-11ea-9929-00163e304a25']
  },
  'product': {
    'id': '8d75bdf3-2d50-11eb-a442-00163e304a25',
    'name': '12',
    'serialNumber': '',
    'type': '',
    'isDelete': 0,
    'createTime': 1606110955000,
    'createUserId': '2e95fcf6-f281-11ea-a442-00163e304a25',
    'createUser': {
      'userId': '2e95fcf6-f281-11ea-a442-00163e304a25',
      'loginName': null,
      'displayName': '李超',
      'email': null,
      'cellPhone': null,
      'lastLoginTime': null,
      'enabled': 1,
      'weixinid': null,
      'powercode': null,
      'head': null,
      'sex': null,
      'firstLogin': 0,
      'tagList': [],
      'departments': null,
      'roles': null,
      'attribute': {},
      'openid': null,
      'longitude': null,
      'latitude': null,
      'isDelete': null,
      'synOpenid': null,
      'staffId': null,
      'tenantId': null,
      'mainTeamId': null,
      'unfinishedTask': null,
      'todayFinishedTask': null,
      'state': null,
      'cusDistance': null,
      'superAdmin': null,
      'isTeamLeader': 0
    },
    'customerId': 'f8cd1a4a-2ae2-11eb-a442-00163e304a25',
    'customerName': '丸子',
    'customerSN': 'CUSDU50456',
    'templateId': null,
    'templateName': null,
    'customer': {
      'createUser': 'd4a478ea-ee73-11ea-a442-00163e304a25',
      'updateUser': null,
      'createTime': null,
      'updateTime': null,
      'id': 'f8cd1a4a-2ae2-11eb-a442-00163e304a25',
      'name': null,
      'enName': null,
      'serialNumber': null,
      'status': null,
      'level': null,
      'superior': null,
      'teamId': null,
      'customerManager': '',
      'customerManagerName': null,
      'remark': null,
      'industry': null,
      'type': null,
      'taskCount': null,
      'productCount': null,
      'isDelete': 0,
      'attribute': {},
      'companyNature': null,
      'tagIds': null,
      'tags': [],
      'createUserId': null,
      'createLoginUser': null,
      'lmName': null,
      'lmPhone': null,
      'lmEmail': null,
      'customerAddress': null,
      'source': null,
      'guideProfessions': [],
      'isGuideData': false,
      'products': [],
      'guideData': false,
      'focus': false
    },
    'customerNumber': null,
    'qrcodeId': null,
    'source': null,
    'guideProfessions': [],
    'isGuideData': false,
    'address': {
      'createUser': null,
      'updateUser': null,
      'createTime': '2020-11-20 11:46:29',
      'updateTime': '2020-11-20 11:46:29',
      'id': 'f8ffba51-2ae2-11eb-a442-00163e304a25',
      'country': '',
      'province': '山东省',
      'city': '青岛市',
      'dist': '市北区',
      'address': '',
      'longitude': 120.37473100,
      'latitude': 36.08760900,
      'isMain': 1,
      'attribute': null,
      'addressType': 0,
      'customerId': 'f8cd1a4a-2ae2-11eb-a442-00163e304a25',
      'guideProfessions': [],
      'isGuideData': false,
      'guideData': false
    },
    'linkman': {
      'createUser': 'd4a478ea-ee73-11ea-a442-00163e304a25',
      'updateUser': 'd4a478ea-ee73-11ea-a442-00163e304a25',
      'createTime': '2020-11-20 11:46:29',
      'updateTime': '2020-11-20 11:46:29',
      'id': 'f9172fb9-2ae2-11eb-a442-00163e304a25',
      'customerId': null,
      'customer': {
        'createUser': null,
        'updateUser': null,
        'createTime': null,
        'updateTime': null,
        'id': 'f8cd1a4a-2ae2-11eb-a442-00163e304a25',
        'name': '丸子',
        'enName': null,
        'serialNumber': null,
        'status': null,
        'level': null,
        'superior': null,
        'teamId': null,
        'customerManager': null,
        'customerManagerName': null,
        'remark': null,
        'industry': null,
        'type': null,
        'taskCount': null,
        'productCount': null,
        'isDelete': null,
        'attribute': {},
        'companyNature': null,
        'tagIds': null,
        'tags': [],
        'createUserId': null,
        'createLoginUser': null,
        'lmName': null,
        'lmPhone': null,
        'lmEmail': null,
        'customerAddress': null,
        'source': null,
        'guideProfessions': [],
        'isGuideData': false,
        'products': [],
        'guideData': false,
        'focus': false
      },
      'name': '紫菀',
      'sex': null,
      'position': null,
      'department': null,
      'isMain': 1,
      'remark': null,
      'phone': '17717282379',
      'email': null,
      'weixin': null,
      'attribute': null,
      'postcode': null,
      'head': null,
      'fax': null,
      'enabled': null,
      'address': null,
      'guideProfessions': [],
      'isGuideData': false,
      'productId': null,
      'tenantId': null,
      'guideData': false
    },
    'updateUserId': 'b9510211-d82f-11e8-b3c6-00163e304a25',
    'updateTime': 1606113438000,
    'updateUser': {
      'userId': 'b9510211-d82f-11e8-b3c6-00163e304a25',
      'loginName': null,
      'displayName': '黄宝成',
      'email': null,
      'cellPhone': null,
      'lastLoginTime': null,
      'enabled': 1,
      'weixinid': null,
      'powercode': null,
      'head': null,
      'sex': null,
      'firstLogin': 0,
      'tagList': [],
      'departments': null,
      'roles': null,
      'attribute': {},
      'openid': null,
      'longitude': null,
      'latitude': null,
      'isDelete': null,
      'synOpenid': null,
      'staffId': null,
      'tenantId': null,
      'mainTeamId': null,
      'unfinishedTask': null,
      'todayFinishedTask': null,
      'state': null,
      'cusDistance': null,
      'superAdmin': null,
      'isTeamLeader': 0
    },
    'attribute': {
      'field_lqkBYbZeANUFNaj7': '1',
      'field_7wGIyf0Rmao5s6Pb': '17664666980',
      'field_HIwM9qQwlKMNxO9L': '34',
      'field_4EZMTGAxlyrVOKuL': '1223',
      'field_x8YIGWgkqlvwMhId': '1189',
      'field_mSY257nkwN48swHL': '2',
      'field_VpAg3J4I9EltaGiK': '3',
      'field_GdP690myfHlLgsW1': '5',
      'field_cozevSH2OPv8F6Nv': '0.666',
      'field_X8C5K7cUpgHFXBqo': '6',
      'field_vmjQ7plaq4DLUzs9': '12',
      'field_OYTI5VFqkybKvjYT': '',
      'field_vphcYoBV7ZhqG4d3': [],
      'field_G3ItKj4znE01DuXL': '',
      'field_VKjhSSsQdtVyKhcO': '',
      'field_4Ok1ifcAPBI1lJ4e': {},
      'field_fgEJptLsBlS3lsod': {},
      'field_kLpVVPFvQdiSjWmF': [],
      'field_650r6t1pBpyl6hAu': ''
    },
    'guideData': false
  },
  'tenantName': '众联成业测试用例企业',
  'eventTypeInfo': [{
    'name': 'chendhTest',
    'id': 'cb7a5fde-22fd-11eb-a442-00163e304a25'
  }, {
    'name': '测试',
    'id': 'e9fc1f93-ba73-11ea-b0e9-00163e304a25'
  }, {
    'name': '刘行测试',
    'id': 'e1434dfb-ccb5-11ea-9929-00163e304a25'
  }, {
    'name': '服务事件',
    'id': 'c387cb94-dc84-11ea-9929-00163e304a25'
  }, {
    'name': 'lxlxlxlxlxlxlxlxl哈哈哈',
    'id': 'e3c05095-98af-11ea-8c0e-00163e304a25'
  }, {
    'name': '示例请求22',
    'id': '23877caa-18b1-4ddb-a924-cb32bb9e1bcd'
  }, {
    'name': '示例服务请求',
    'id': 'e7f21d83-9fe3-4559-8a61-5aa1b0743612'
  }, {
    'name': '客户问题反馈',
    'id': '96e39dab-a18f-4750-9a28-1599a69c2634'
  }, {
    'name': '客户报修',
    'id': '4ee1f052-3aed-4836-bb90-5d12d6942e53'
  }, {
    'name': '千一的事件类',
    'id': '46272be1-ecc7-11e9-bfc9-00163e304a25'
  }, {
    'name': '微商',
    'id': '0ae54def-f17d-11e8-b3c6-00163e304a25'
  }, {
    'name': '示例服务请求',
    'id': '817729dd-4345-4e75-90bc-3b7eee69923b'
  }, {
    'name': '移动端勿动2',
    'id': '6dd88aab-d3ef-11e7-9070-00163e304a25'
  }, {
    'name': '事件关联产品',
    'id': '1bbfe0af-51ae-11e8-8546-00163e304a25'
  }, {
    'name': '测试导出',
    'id': '262110de-8353-11e8-8546-00163e304a25'
  }, {
    'name': '批量编辑测试',
    'id': '2cacb95e-58f8-11e8-8546-00163e304a25'
  }, {
    'name': '测试事件',
    'id': '66736655-dd75-11e8-b3c6-00163e304a25'
  }, {
    'name': '测试导出副本',
    'id': '8e83f7a9-9607-11e8-b3c6-00163e304a25'
  }, {
    'name': 'API事件',
    'id': '55072b50-04e8-11e9-b3c6-00163e304a25'
  }, {
    'name': '测试转工单',
    'id': '954fed48-2f63-11e9-b3c6-00163e304a25'
  }],
  'nickName': '公司简称长度不得超过公司简称长度不得超过',
  'domain': 102308,
  'productFields': [{
    'id': 7192,
    'tenantId': '7416b42a-25cc-11e7-a500-00163e12f748',
    'tableName': 'product',
    'isSystem': 0,
    'fieldName': 'field_mSY257nkwN48swHL',
    'displayName': '数字1',
    'formType': 'number',
    'defaultValue': '1',
    'isNull': 1,
    'isSearch': 0,
    'placeHolder': null,
    'setting': {
      'defaultValueConfig': {
        'isNotModify': 0
      }
    },
    'orderId': 0,
    'isDelete': 0,
    'guideProfessions': [],
    'isGuideData': false,
    'isVisible': true,
    'isHidden': 0,
    'guideData': false
  }, {
    'id': 7193,
    'tenantId': '7416b42a-25cc-11e7-a500-00163e12f748',
    'tableName': 'product',
    'isSystem': 0,
    'fieldName': 'field_VpAg3J4I9EltaGiK',
    'displayName': '数字2',
    'formType': 'number',
    'defaultValue': null,
    'isNull': 1,
    'isSearch': 1,
    'placeHolder': null,
    'setting': {},
    'orderId': 1,
    'isDelete': 0,
    'guideProfessions': [],
    'isGuideData': false,
    'isVisible': true,
    'isHidden': 0,
    'guideData': false
  }, {
    'id': 7183,
    'tenantId': '7416b42a-25cc-11e7-a500-00163e12f748',
    'tableName': 'product',
    'isSystem': 0,
    'fieldName': 'field_GdP690myfHlLgsW1',
    'displayName': '计算公式',
    'formType': 'formula',
    'defaultValue': null,
    'isNull': 1,
    'isSearch': 1,
    'placeHolder': null,
    'setting': {
      'formula': [{
        'name': '数字1',
        'value': 'field_mSY257nkwN48swHL',
        'isError': false,
        'isDelete': false,
        'isOperator': false
      }, {
        'name': '/',
        'value': '/',
        'isError': false,
        'isDelete': false,
        'isOperator': true
      }, {
        'name': '数字2',
        'value': 'field_VpAg3J4I9EltaGiK',
        'isError': false,
        'isDelete': false,
        'isOperator': false
      }],
      'defaultValueConfig': {
        'isNotModify': 0
      }
    },
    'orderId': 2,
    'isDelete': 0,
    'guideProfessions': [],
    'isGuideData': false,
    'isVisible': true,
    'isHidden': 0,
    'guideData': false
  }, {
    'id': 1149,
    'tenantId': '7416b42a-25cc-11e7-a500-00163e12f748',
    'tableName': 'product',
    'isSystem': 1,
    'fieldName': 'serialNumber',
    'displayName': '产品编号',
    'formType': 'text',
    'defaultValue': null,
    'isNull': 1,
    'isSearch': 0,
    'placeHolder': '请输入产品编号test',
    'setting': {
      'serialNumberUnique': false
    },
    'orderId': 3,
    'isDelete': 0,
    'guideProfessions': [],
    'isGuideData': false,
    'isVisible': true,
    'isHidden': 0,
    'guideData': false
  }, {
    'id': 1150,
    'tenantId': '7416b42a-25cc-11e7-a500-00163e12f748',
    'tableName': 'product',
    'isSystem': 1,
    'fieldName': 'name',
    'displayName': '产品名称',
    'formType': 'text',
    'defaultValue': null,
    'isNull': 0,
    'isSearch': 0,
    'placeHolder': '请输入产品名称test',
    'setting': {},
    'orderId': 4,
    'isDelete': 0,
    'guideProfessions': [],
    'isGuideData': false,
    'isVisible': true,
    'isHidden': 0,
    'guideData': false
  }, {
    'id': 1151,
    'tenantId': '7416b42a-25cc-11e7-a500-00163e12f748',
    'tableName': 'product',
    'isSystem': 1,
    'fieldName': 'type',
    'displayName': '产品类型',
    'formType': 'select',
    'defaultValue': null,
    'isNull': 1,
    'isSearch': 0,
    'placeHolder': '请选择产品类型',
    'setting': {
      'isMulti': false,
      'dataSource': ['电器', '厨具', '空调']
    },
    'orderId': 5,
    'isDelete': 0,
    'guideProfessions': [],
    'isGuideData': false,
    'isVisible': true,
    'isHidden': 0,
    'guideData': false
  }, {
    'id': 7165,
    'tenantId': '7416b42a-25cc-11e7-a500-00163e12f748',
    'tableName': 'product',
    'isSystem': 0,
    'fieldName': 'field_OYTI5VFqkybKvjYT',
    'displayName': '日期 （年月）',
    'formType': 'date',
    'defaultValue': null,
    'isNull': 1,
    'isSearch': 0,
    'placeHolder': null,
    'setting': {
      'dateType': 'yyyy-MM'
    },
    'orderId': 6,
    'isDelete': 0,
    'guideProfessions': [],
    'isGuideData': false,
    'isVisible': true,
    'isHidden': 0,
    'guideData': false
  }, {
    'id': 1148,
    'tenantId': '7416b42a-25cc-11e7-a500-00163e12f748',
    'tableName': 'product',
    'isSystem': 1,
    'fieldName': 'customer',
    'displayName': '客户',
    'formType': 'customer',
    'defaultValue': null,
    'isNull': 0,
    'isSearch': 0,
    'placeHolder': null,
    'setting': {
      'customerOption': {
        'address': true,
        'linkman': true,
        'addressNotNull': false,
        'linkmanNotNull': false
      }
    },
    'orderId': 7,
    'isDelete': 0,
    'guideProfessions': [],
    'isGuideData': false,
    'isVisible': true,
    'isHidden': 0,
    'guideData': false
  }, {
    'id': 7166,
    'tenantId': '7416b42a-25cc-11e7-a500-00163e12f748',
    'tableName': 'product',
    'isSystem': 0,
    'fieldName': 'field_vphcYoBV7ZhqG4d3',
    'displayName': '多级菜单',
    'formType': 'cascader',
    'defaultValue': '',
    'isNull': 1,
    'isSearch': 0,
    'placeHolder': null,
    'setting': {
      'maxDeep': 5,
      'dataSource': [{
        'value': '一级选项 1',
        'children': [{
          'value': '二级选项 1',
          'children': [{
            'value': '三级选项 1',
            'children': [{
              'value': '四级选项 1',
              'children': [{
                'value': '五级选项 1'
              }]
            }]
          }]
        }]
      }, {
        'value': '电器',
        'children': [{
          'value': '电视',
          'children': [{
            'value': '三级选项 1',
            'children': [{
              'value': '四级选项 1',
              'children': [{
                'value': '五级选项 1'
              }]
            }]
          }]
        }, {
          'value': '冰箱',
          'children': [{
            'value': '三级选项 1',
            'children': [{
              'value': '四级选项 1',
              'children': [{
                'value': '五级选项 1'
              }]
            }]
          }]
        }]
      }, {
        'value': '一级选项 2',
        'children': [{
          'value': '二级选项 1',
          'children': [{
            'value': '三级选项 1',
            'children': [{
              'value': '四级选项 1',
              'children': [{
                'value': '五级选项 1'
              }]
            }]
          }]
        }, {
          'value': '二级选项 2',
          'children': [{
            'value': '三级选项 1',
            'children': [{
              'value': '四级选项 1',
              'children': [{
                'value': '五级选项 1'
              }]
            }]
          }]
        }]
      }]
    },
    'orderId': 8,
    'isDelete': 0,
    'guideProfessions': [],
    'isGuideData': false,
    'isVisible': true,
    'isHidden': 0,
    'guideData': false
  }, {
    'id': 7167,
    'tenantId': '7416b42a-25cc-11e7-a500-00163e12f748',
    'tableName': 'product',
    'isSystem': 0,
    'fieldName': 'field_G3ItKj4znE01DuXL',
    'displayName': '单行文本',
    'formType': 'text',
    'defaultValue': null,
    'isNull': 1,
    'isSearch': 0,
    'placeHolder': null,
    'setting': {},
    'orderId': 9,
    'isDelete': 0,
    'guideProfessions': [],
    'isGuideData': false,
    'isVisible': true,
    'isHidden': 0,
    'guideData': false
  }, {
    'id': 7168,
    'tenantId': '7416b42a-25cc-11e7-a500-00163e12f748',
    'tableName': 'product',
    'isSystem': 0,
    'fieldName': 'field_VKjhSSsQdtVyKhcO',
    'displayName': '数字',
    'formType': 'number',
    'defaultValue': null,
    'isNull': 1,
    'isSearch': 0,
    'placeHolder': null,
    'setting': {},
    'orderId': 10,
    'isDelete': 0,
    'guideProfessions': [],
    'isGuideData': false,
    'isVisible': true,
    'isHidden': 0,
    'guideData': false
  }, {
    'id': 7169,
    'tenantId': '7416b42a-25cc-11e7-a500-00163e12f748',
    'tableName': 'product',
    'isSystem': 0,
    'fieldName': 'field_4Ok1ifcAPBI1lJ4e',
    'displayName': '人员',
    'formType': 'user',
    'defaultValue': null,
    'isNull': 1,
    'isSearch': 0,
    'placeHolder': null,
    'setting': {},
    'orderId': 11,
    'isDelete': 0,
    'guideProfessions': [],
    'isGuideData': false,
    'isVisible': true,
    'isHidden': 0,
    'guideData': false
  }, {
    'id': 7172,
    'tenantId': '7416b42a-25cc-11e7-a500-00163e12f748',
    'tableName': 'product',
    'isSystem': 0,
    'fieldName': 'field_fgEJptLsBlS3lsod',
    'displayName': '地址',
    'formType': 'address',
    'defaultValue': null,
    'isNull': 1,
    'isSearch': 0,
    'placeHolder': null,
    'setting': {},
    'orderId': 12,
    'isDelete': 0,
    'guideProfessions': [],
    'isGuideData': false,
    'isVisible': true,
    'isHidden': 0,
    'guideData': false
  }, {
    'id': 7239,
    'tenantId': '7416b42a-25cc-11e7-a500-00163e12f748',
    'tableName': 'product',
    'isSystem': 0,
    'fieldName': 'field_kLpVVPFvQdiSjWmF',
    'displayName': '附件',
    'formType': 'attachment',
    'defaultValue': null,
    'isNull': 1,
    'isSearch': 0,
    'placeHolder': null,
    'setting': {},
    'orderId': 13,
    'isDelete': 0,
    'guideProfessions': [],
    'isGuideData': false,
    'isVisible': true,
    'isHidden': 0,
    'guideData': false
  }, {
    'id': 7299,
    'tenantId': '7416b42a-25cc-11e7-a500-00163e12f748',
    'tableName': 'product',
    'isSystem': 0,
    'fieldName': 'field_Q3tkenLSjcCoNM6p',
    'displayName': '电话',
    'formType': 'phone',
    'defaultValue': null,
    'isNull': 1,
    'isSearch': 0,
    'placeHolder': null,
    'setting': {
      'defaultValueConfig': {
        'isCurrentPhone': 1
      }
    },
    'orderId': 14,
    'isDelete': 0,
    'guideProfessions': [],
    'isGuideData': false,
    'isVisible': true,
    'isHidden': 0,
    'guideData': false
  }],
  'taskTypeInfo': [{
    'name': 'test工单',
    'id': '4e67dcdb-f386-473a-ba24-1b53d7b5da77'
  }, {
    'name': 'xuan新建测试',
    'id': '78571fba-1694-46f7-b8f5-8cee7562e293'
  }, {
    'name': 'jimbei',
    'id': 'fbf26cfe-b906-4a52-8d27-3d59a6cca0ca'
  }, {
    'name': '最新的最新的最新的最新的最新的最新的最新',
    'id': '9a027005-7cfe-4c41-a98b-8b74bdf51b29'
  }, {
    'name': '测试工单池',
    'id': '751df004-179d-4095-bdc1-5cb786626741'
  }, {
    'name': '默认工单',
    'id': '1'
  }],
  'productConfig': {
    'productType': ['电器', '厨具', '空调'],
    'productSearchOnMobile': true,
    'serialNumberUnique': false,
    'qrcodeEnabled': true,
    'productTypeIsNull': false,
    'fieldNameList': ['serialNumber', 'name', 'type'],
    'hideDefaultLinkman': true
  },
  'planTaskEnabled': true
}
export default obj