const searchCustomer = {
  pageNum: 1,
  pageSize: 10,
  size: 0,
  orderBy: null,
  startRow: 0,
  endRow: 0,
  total: 0,
  pages: 0,
  list: [
    {
      createUser: 'f86882b4-3f87-11eb-9baf-00163e0d174e',
      updateUser: '94f920b1-ee5e-11ea-879a-00163e0f1a1b',
      createTime: '2020-12-24 11:46:24',
      updateTime: '2021-01-05 16:36:51',
      id: '97fd567a-459a-11eb-9baf-00163e0d174e',
      name: '谷理想',
      enName: null,
      serialNumber: 'CUSAZ02192',
      status: 1,
      level: null,
      superior: null,
      teamId: null,
      customerManager: 'f86882b4-3f87-11eb-9baf-00163e0d174e',
      customerManagerName: '谷理想（离乡）',
      remark: null,
      industry: null,
      type: null,
      taskCount: null,
      productCount: null,
      isDelete: 0,
      attribute: {
        field_ZaGivaS4Rb2wc9s2: '',
        field_ajM77Yx1v4dP86qC: {},
        field_WTYx8sZZ41yM4vM1: '',
        field_w3vzcNtnhI8XCUaj: {},
        field_txpMFsTGmFiON1Qp: '',
        field_o9UU59bnXf2VSiXj: {
          all: '河南省周口市项城市、、、',
          address: '、、、',
          province: '河南省',
          city: '周口市',
          addressType: 0,
          latitude: '',
          dist: '项城市',
          longitude: '',
        },
        remindCount: '0',
        field_UtaDxoNwZ9K4IGMP: '',
        field_MOKCegqge4bfnNyq: '',
        field_dvoqrjOcMJ9ovEys: [
          {
            head:
              'https://static-legacy.dingtalk.com/media/lADPD3lGsh0-1YfNAzDNAqU_677_816.jpg',
            displayName: '谷理想（离乡）',
            userId: 'f86882b4-3f87-11eb-9baf-00163e0d174e',
            staffId: '0462334311238407135',
          },
        ],
        field_BRaM3WD9tpbHyPRp: '',
        field_E6ZZq1Ene3okPv3n: '',
        field_xoMMrKz3xJNmVDLz: '',
        field_XnCYEIYopJlpNUkt: [],
        field_TD5sGADBmYn88Cgt: '',
        field_IIMSodzNSBoCOJQV: [],
        field_MazHdpkQmZ7CdwCa: '单行默认值',
        field_2mrGfTdSdJMjZsjh: '',
        field_aCyell1nbSIeBoqx: '',
        field_oYAgRGvJWLVhugAZ: '',
        field_splrixD7nCebnRiJ: '',
        field_5vt8bvinYts1HVXC: '18661042350',
        field_niaoDMUfiT34GyR6: [],
        field_ylSlEWowyMDoSaXF: '',
        field_ZgFaU4SWN9NPEb2i: '多行默认',
        field_WtRT3BJXXMym1Hcu: '5',
        field_3GSZaCn44SwT1Hcl: '',
        field_GaGO2SbiYgOXUXTa: '',
        field_l0Bbnh6cE3PUP5xh: '',
        field_E21fSa3FUB0yLzxI: '',
        field_s8j9hWB6Z0jeW5Wo: '',
      },
      companyNature: null,
      tagIds: null,
      tags: [
        { id: '54a39731-459a-11eb-9baf-00163e0d174e', tagName: '归乡团队' },
      ],
      createUserId: null,
      createLoginUser: {
        userId: 'f86882b4-3f87-11eb-9baf-00163e0d174e',
        loginName: null,
        displayName: '谷理想（离乡）',
        email: null,
        cellPhone: null,
        lastLoginTime: null,
        enabled: 1,
        weixinid: null,
        powercode: null,
        head: null,
        sex: null,
        firstLogin: 0,
        tagList: [],
        departments: null,
        roles: null,
        attribute: {},
        openid: null,
        longitude: null,
        latitude: null,
        isDelete: null,
        synOpenid: null,
        staffId: null,
        tenantId: null,
        mainTeamId: null,
        unfinishedTask: null,
        todayFinishedTask: null,
        state: null,
        cusDistance: null,
        wechat: null,
        superAdmin: null,
        isTeamLeader: 0,
      },
      lmName: '谷理想',
      lmPhone: '18661042350',
      lmEmail: null,
      customerAddress: {
        adCountry: '',
        adDist: '项城市',
        adProvince: '河南省',
        adCity: '周口市',
        adAddress: '老街',
        adLongitude: 114.875333,
        adLatitude: 33.465838,
        addressType: 0,
        validAddress: true,
      },
      source: null,
      guideProfessions: null,
      isGuideData: false,
      products: [],
      guideData: false,
      focus: false,
    },
    {
      createUser: 'f415e7d0-ed83-11ea-879a-00163e0f1a1b',
      updateUser: 'e127a447-0e1b-11eb-9baf-00163e0d174e',
      createTime: '2020-12-24 11:22:58',
      updateTime: '2020-12-25 18:05:26',
      id: '5197878f-4597-11eb-9baf-00163e0d174e',
      name: 'WANZI丸子',
      enName: null,
      serialNumber: 'CUSGU02191',
      status: 1,
      level: null,
      superior: null,
      teamId: null,
      customerManager: null,
      customerManagerName: null,
      remark: null,
      industry: null,
      type: null,
      taskCount: null,
      productCount: null,
      isDelete: 0,
      attribute: {
        field_ZaGivaS4Rb2wc9s2: '123',
        field_ajM77Yx1v4dP86qC: {},
        field_WTYx8sZZ41yM4vM1: '1',
        field_w3vzcNtnhI8XCUaj: {
          head: '',
          displayName: '何家乐',
          userId: '30882d62-31f0-11ea-9ddd-00163e0f1a1b',
          staffId: '216159572920264815',
        },
        field_txpMFsTGmFiON1Qp: '1',
        field_o9UU59bnXf2VSiXj: {
          all: '',
          address: '',
          province: '',
          city: '',
          addressType: 0,
          dist: '',
        },
        field_UtaDxoNwZ9K4IGMP: '2',
        field_MOKCegqge4bfnNyq: '',
        field_dvoqrjOcMJ9ovEys: [
          {
            head:
              'https://static-legacy.dingtalk.com/media/lADPDhmOtN8J_hrNAvDNAu4_750_752.jpg',
            displayName: '万万',
            userId: 'f415e7d0-ed83-11ea-879a-00163e0f1a1b',
            staffId: '2703050024639200',
          },
        ],
        field_BRaM3WD9tpbHyPRp: '55',
        field_E6ZZq1Ene3okPv3n: '2018-01-01 00:00:00',
        field_xoMMrKz3xJNmVDLz: '',
        field_XnCYEIYopJlpNUkt: ['好', '了'],
        field_TD5sGADBmYn88Cgt: '',
        field_IIMSodzNSBoCOJQV: ['一'],
        field_MazHdpkQmZ7CdwCa: '单行默认值',
        field_2mrGfTdSdJMjZsjh: '3.1232099999999998',
        field_aCyell1nbSIeBoqx: '2018-01-01 00:55',
        field_oYAgRGvJWLVhugAZ: '2018-01-01 00:00:00',
        field_splrixD7nCebnRiJ: '123',
        field_5vt8bvinYts1HVXC: '123456',
        field_niaoDMUfiT34GyR6: [],
        field_ylSlEWowyMDoSaXF: '2018-03',
        field_ZgFaU4SWN9NPEb2i: '多行默认',
        field_WtRT3BJXXMym1Hcu: '5',
        field_3GSZaCn44SwT1Hcl: '123456',
        field_GaGO2SbiYgOXUXTa: '1',
        field_l0Bbnh6cE3PUP5xh: '2018-01-01',
        field_E21fSa3FUB0yLzxI: '231313@qq.com',
        field_s8j9hWB6Z0jeW5Wo: '3',
      },
      companyNature: null,
      tagIds: null,
      tags: [],
      createUserId: null,
      createLoginUser: {
        userId: 'f415e7d0-ed83-11ea-879a-00163e0f1a1b',
        loginName: null,
        displayName: '万万',
        email: null,
        cellPhone: null,
        lastLoginTime: null,
        enabled: 1,
        weixinid: null,
        powercode: null,
        head: null,
        sex: null,
        firstLogin: 0,
        tagList: [],
        departments: null,
        roles: null,
        attribute: {},
        openid: null,
        longitude: null,
        latitude: null,
        isDelete: null,
        synOpenid: null,
        staffId: null,
        tenantId: null,
        mainTeamId: null,
        unfinishedTask: null,
        todayFinishedTask: null,
        state: null,
        cusDistance: null,
        wechat: null,
        superAdmin: null,
        isTeamLeader: 0,
      },
      lmName: 'WANZI丸子',
      lmPhone: '021-2321323',
      lmEmail: null,
      customerAddress: {
        adCountry: '',
        adDist: '',
        adProvince: '',
        adCity: '',
        adAddress: '',
        adLongitude: null,
        adLatitude: null,
        addressType: 0,
        validAddress: false,
      },
      source: null,
      guideProfessions: null,
      isGuideData: false,
      products: [],
      guideData: false,
      focus: false,
    },
  ],
  firstPage: 0,
  prePage: 0,
  nextPage: 0,
  lastPage: 0,
  isFirstPage: true,
  isLastPage: false,
  hasPreviousPage: false,
  hasNextPage: false,
  navigatePages: 0,
  navigatepageNums: null,
};
const searchAddress = {
  status: 0,
  message: 'ok',
  data: [
    {
      createUser: null,
      updateUser: 'f86882b4-3f87-11eb-9baf-00163e0d174e',
      createTime: '2020-12-24 11:46:24',
      updateTime: '2020-12-24 15:17:46',
      id: '9803df2e-459a-11eb-9baf-00163e0d174e',
      country: '',
      province: '河南省',
      city: '周口市',
      dist: '项城市',
      address: '老街',
      longitude: 114.875333,
      latitude: 33.465838,
      isMain: 1,
      attribute: null,
      addressType: 0,
      customerId: '97fd567a-459a-11eb-9baf-00163e0d174e',
      guideProfessions: [],
      isGuideData: false,
      guideData: false,
    },
  ],
  succ: true,
};
const searchLinkman = {
  success: true,
  code: 0,
  message: '查询成功',
  result: {
    pageNum: 0,
    pageSize: 0,
    size: 1,
    startRow: 1,
    endRow: 1,
    total: 1,
    pages: 0,
    list: [
      {
        id: '9805cb84-459a-11eb-9baf-00163e0d174e',
        name: '谷理想',
        phone: '18661042350',
        isMain: 1,
      },
    ],
    prePage: 0,
    nextPage: 0,
    isFirstPage: false,
    isLastPage: true,
    hasPreviousPage: false,
    hasNextPage: false,
    navigatePages: 8,
    navigatepageNums: [],
    navigateFirstPage: 0,
    navigateLastPage: 0,
    firstPage: 0,
    lastPage: 0,
  },
};
const searchLinkmanSb = {
  status: 0,
  message: 'ok',
  data: [
    {
      createUser: 'f86882b4-3f87-11eb-9baf-00163e0d174e',
      updateUser: 'f86882b4-3f87-11eb-9baf-00163e0d174e',
      createTime: '2020-12-24 11:46:24',
      updateTime: '2020-12-24 15:17:46',
      id: '9805cb84-459a-11eb-9baf-00163e0d174e',
      customerId: null,
      customer: {
        createUser: null,
        updateUser: null,
        createTime: null,
        updateTime: null,
        id: '97fd567a-459a-11eb-9baf-00163e0d174e',
        name: '谷理想',
        enName: null,
        serialNumber: null,
        status: null,
        level: null,
        superior: null,
        teamId: null,
        customerManager: null,
        customerManagerName: null,
        remark: null,
        industry: null,
        type: null,
        taskCount: null,
        productCount: null,
        isDelete: null,
        attribute: {},
        companyNature: null,
        tagIds: null,
        tags: [],
        createUserId: null,
        createLoginUser: null,
        lmName: null,
        lmPhone: null,
        lmEmail: null,
        customerAddress: {
          adCountry: '',
          adDist: '项城市',
          adProvince: '河南省',
          adCity: '周口市',
          adAddress: '老街',
          adLongitude: 114.875333,
          adLatitude: 33.465838,
          addressType: 0,
          validAddress: true,
        },
        source: null,
        guideProfessions: [],
        isGuideData: false,
        products: [],
        guideData: false,
        focus: false,
      },
      name: '谷理想',
      sex: null,
      position: null,
      department: null,
      isMain: 1,
      remark: null,
      phone: '18661042350',
      email: null,
      weixin: null,
      attribute: null,
      postcode: null,
      head: null,
      fax: null,
      enabled: null,
      address: null,
      guideProfessions: [],
      isGuideData: false,
      productId: null,
      tenantId: null,
      guideData: false,
    },
  ],
  succ: true,
};
const searchProduct = {
  pageNum: 1,
  pageSize: 10,
  size: 1,
  orderBy: null,
  startRow: 0,
  endRow: 0,
  total: 1,
  pages: 1,
  list: [
    {
      id: 'f57387f9-4a75-11eb-9baf-00163e0d174e',
      name: '奔驰E63s-磨砂黑',
      serialNumber: 'WLH9999',
      type: '保健品2',
      isDelete: 0,
      createTime: 1609315605000,
      createUserId: null,
      createUser: {
        userId: '83e6e320-32f2-11eb-9baf-00163e0d174e',
        loginName: null,
        displayName: '乐天',
        email: null,
        cellPhone: null,
        lastLoginTime: null,
        enabled: 1,
        weixinid: null,
        powercode: null,
        head: null,
        sex: null,
        firstLogin: 0,
        tagList: [],
        departments: null,
        roles: null,
        attribute: {},
        openid: null,
        longitude: null,
        latitude: null,
        isDelete: null,
        synOpenid: null,
        staffId: null,
        tenantId: null,
        mainTeamId: null,
        unfinishedTask: null,
        todayFinishedTask: null,
        state: null,
        cusDistance: null,
        wechat: null,
        superAdmin: null,
        isTeamLeader: 0,
      },
      customerId: '97fd567a-459a-11eb-9baf-00163e0d174e',
      customerName: '谷理想',
      customerSN: 'CUSAZ02192',
      templateId: null,
      templateName: null,
      customer: {
        createUser: null,
        updateUser: null,
        createTime: null,
        updateTime: null,
        id: '97fd567a-459a-11eb-9baf-00163e0d174e',
        name: '谷理想',
        enName: null,
        serialNumber: null,
        status: null,
        level: null,
        superior: null,
        teamId: null,
        customerManager: 'f86882b4-3f87-11eb-9baf-00163e0d174e',
        customerManagerName: null,
        remark: null,
        industry: null,
        type: null,
        taskCount: null,
        productCount: null,
        isDelete: null,
        attribute: {},
        companyNature: null,
        tagIds: null,
        tags: [
          { id: '54a39731-459a-11eb-9baf-00163e0d174e', tagName: '归乡团队' },
        ],
        createUserId: null,
        createLoginUser: null,
        lmName: null,
        lmPhone: null,
        lmEmail: null,
        customerAddress: null,
        source: null,
        guideProfessions: [],
        isGuideData: false,
        products: [],
        guideData: false,
        focus: false,
      },
      customerNumber: null,
      qrcodeId: '100093',
      source: '内部创建',
      guideProfessions: [],
      isGuideData: false,
      address: null,
      linkman: null,
      catalogId: null,
      catalogPathName: null,
      catalogNum: null,
      updateUserId: null,
      updateTime: 1609835811000,
      updateUser: {
        userId: '94f920b1-ee5e-11ea-879a-00163e0f1a1b',
        loginName: null,
        displayName: '德芙*',
        email: null,
        cellPhone: null,
        lastLoginTime: null,
        enabled: 1,
        weixinid: null,
        powercode: null,
        head: null,
        sex: null,
        firstLogin: 0,
        tagList: [],
        departments: null,
        roles: null,
        attribute: {},
        openid: null,
        longitude: null,
        latitude: null,
        isDelete: null,
        synOpenid: null,
        staffId: null,
        tenantId: null,
        mainTeamId: null,
        unfinishedTask: null,
        todayFinishedTask: null,
        state: null,
        cusDistance: null,
        wechat: null,
        superAdmin: null,
        isTeamLeader: 0,
      },
      attribute: {
        field_MxlPpbgCr6RVAln6: '',
        field_nUs5iyoXzhNjV2aK: {},
        field_WRfziGrRVaLpjqIb: '',
        field_vD3jYuAUuzF0x9e1: '',
        field_I76qd1Q9YjlofPwv: '',
        field_wexoaX4jYW0QQYDo: {},
        field_x9HOWbtTbWnJyXVa: '',
        field_0kMzX4pFbLqWZyFn: '',
        field_Q3I7L09Kw1jAt5FB: {},
        remindCount: 0,
        field_IlxhBi0VAv2jMYpm: [],
      },
      guideData: false,
    },
  ],
  firstPage: 0,
  prePage: 0,
  nextPage: 0,
  lastPage: 0,
  isFirstPage: true,
  isLastPage: true,
  hasPreviousPage: false,
  hasNextPage: false,
  navigatePages: 0,
  navigatepageNums: null,
};

export {
  searchCustomer,
  searchAddress,
  searchLinkman,
  searchProduct,
  searchLinkmanSb,
};
