let obj = {
  loginUser: {
    displayName: "薄德忠",
    roles: ["1"],
    tagIds: [
      "a3dda245-e5df-11ea-9929-00163e304a25",
      "fc637ab7-e76d-11ea-9929-00163e304a25",
    ],
    userId: "6839d043-683e-11ea-bfc9-00163e304a25",
    authorities: {
      TASK_ADD: 3,
      PRODUCT_CREATE: 3,
      CUSTOMER_CREATE: 3,
      VIP_PAYMENT_ONLINE: 3,
      TASK_BATCH_DISPATCH: 3,
      CASE_ADD: 3,
      SERVICE_CREATE: 3,
      CASE_VIEW: 3,
      TASK_EDIT: 3,
      TASK_FEEDBACK: 3,
      VIP_INFO_NOTICE_SELECT: 3,
      LOGIN_PC: 3,
      SMS_CONFIG: 3,
      VIP_INFO_NOTICE_CREATE: 3,
      SERVICE_EDIT: 3,
      PORTAL_ORDER: 3,
      PRODUCT_EDIT: 3,
      VIP_SPAREPART_BACK: 3,
      TASK_DISPATCH: 3,
      TASK_POOL: 3,
      VIP_REPORT_VIEW: 3,
      TASK_VIEW: 3,
      AUTH_STAFF: 3,
      AUTH_ROLE: 3,
      TASK_CLOSE: 3,
      TASK_BATCH_CLOSE: 3,
      VIP_SPAREPART_PERSION: 3,
      INFO_EDIT: 3,
      VIP_SPAREPART_INOUT: 3,
      TASK_AUDIT: 3,
      PRODUCT_VIEW: 3,
      CUSTOMER_DELETE: 3,
      CASE_DELETE: 3,
      INFO_VIEW: 3,
      EXPORT_IN: 3,
      VIP_APPROVE: 3,
      PART_EDIT: 3,
      SERVICE_VIEW: 3,
      CUSTOMER_VIEW: 3,
      VIP_SPAREPART_CREATE: 3,
      VIP_SPAREPART_VIEW: 3,
      CUSTOMER_PQRCODE: 3,
      TASK_DELETE: 3,
      VIP_TASK_PLAN: 3,
      PRODUCT_DELETE: 3,
      CASE_EDIT: 3,
      VIP_INFO_CREATE: 3,
      SYSTEM_SEETING: 3,
      LOGIN_YD: 3,
      VIP_SPAREPART_EDIT: 3,
      PART_VIEW: 3,
      AUTH_TAG: 3,
      VIP_SPAREPART_STOCK: 3,
      TASK_BATCH_AUDIT: 3,
      CUSTOMER_EDIT: 3,
    },
    tagIdsWithChildTag: [
      "08e1d3bb-ed84-11ea-a442-00163e304a25",
      "a3dda245-e5df-11ea-9929-00163e304a25",
      "fc637ab7-e76d-11ea-9929-00163e304a25",
    ],
  },
  productFields: [
    {
      id: 7520,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_jk09l05Ll8lGFhVY",
      displayName: "下拉菜单",
      formType: "select",
      defaultValue: null,
      isNull: 1,
      isSearch: 1,
      placeHolder: null,
      setting: {
        isMulti: true,
        dataSource: ["下拉菜单1", "下拉菜单2", "下拉菜单3"],
        selectType: 2,
      },
      orderId: 0,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7167,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_G3ItKj4znE01DuXL",
      displayName: "单行文本1",
      formType: "text",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: {},
      orderId: 1,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7499,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_SKBzJEeVDkDIMdNR",
      displayName: "多级菜单1",
      formType: "cascader",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: {
        maxDeep: 2,
        dataSource: [
          { value: "一级选项 1", children: [{ value: "二级选项 1" }] },
        ],
      },
      orderId: 2,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 1149,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 1,
      fieldName: "serialNumber",
      displayName: "产品编号",
      formType: "text",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: "请输入产品编号test",
      setting: { serialNumberUnique: false },
      orderId: 3,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 1150,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 1,
      fieldName: "name",
      displayName: "产品名称",
      formType: "text",
      defaultValue: null,
      isNull: 0,
      isSearch: 0,
      placeHolder: "请输入产品名称test",
      setting: {},
      orderId: 4,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 1151,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 1,
      fieldName: "type",
      displayName: "产品类型",
      formType: "select",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: "请选择产品类型",
      setting: { isMulti: false, dataSource: ["电器", "厨具", "空调"] },
      orderId: 5,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 1148,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 1,
      fieldName: "customer",
      displayName: "客户",
      formType: "customer",
      defaultValue: null,
      isNull: 0,
      isSearch: 0,
      placeHolder: null,
      setting: {
        customerOption: {
          address: true,
          linkman: true,
          addressNotNull: true,
          linkmanNotNull: true,
        },
      },
      orderId: 6,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7454,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_spQQ3pcVUj2aGpcS",
      displayName: "多行文本",
      formType: "textarea",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: {},
      orderId: 7,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7537,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 1,
      fieldName: "catalogId",
      displayName: "产品目录",
      formType: "related_catalog",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: {},
      orderId: 8,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7455,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_bpnudZlEo5qPWGyh",
      displayName: "数字",
      formType: "number",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: {},
      orderId: 9,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7456,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_n5IWATskN7kygipO",
      displayName: "下拉菜单",
      formType: "select",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: { isMulti: false, dataSource: ["1", "2", "3"] },
      orderId: 10,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7457,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_qdVyMnpSVgjKVhdC",
      displayName: "多级菜单",
      formType: "cascader",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: {
        maxDeep: 2,
        dataSource: [
          { value: "一级选项 1", children: [{ value: "二级选项 1" }] },
        ],
      },
      orderId: 11,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7458,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_eySOwB7KTtXhg0Ez",
      displayName: "附件",
      formType: "attachment",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: {},
      orderId: 12,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7459,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_Yzy3A3NGg8vJRgk7",
      displayName: "人员",
      formType: "user",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: {},
      orderId: 13,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7460,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_L0Ar1baS3omwzjYH",
      displayName: "日期",
      formType: "date",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: {},
      orderId: 14,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7461,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_7lbsroWKQ3pBwqgC",
      displayName: "日期时间",
      formType: "datetime",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: {},
      orderId: 15,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7462,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_hVIatA4Vvmav7adL",
      displayName: "电话",
      formType: "phone",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: {},
      orderId: 16,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7463,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_2MFkwKM3DEYNOf2I",
      displayName: "邮箱",
      formType: "email",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: {},
      orderId: 17,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7464,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_aQV60BizbyO9Y9Xk",
      displayName: "分割线",
      formType: "separator",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: {},
      orderId: 18,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7465,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_SG2IOtxZ4BYeIRov",
      displayName: "地址",
      formType: "address",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: {},
      orderId: 19,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7466,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_ubBK8OhAVUAvMdkN",
      displayName: "位置",
      formType: "location",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: {},
      orderId: 20,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7467,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_5XeMxAx2jQnzxqy4",
      displayName: "说明信息",
      formType: "info",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder:
        "请输入说明信息，说明信息只是在表单中增加内容描述，不能做任何输入。",
      setting: {},
      orderId: 21,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7468,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_MNrQF88gB45g4a0h",
      displayName: "电子签名",
      formType: "autograph",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: {},
      orderId: 22,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7469,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_Q8QdXbGxA2ORUn0J",
      displayName: "关联工单",
      formType: "related_task",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: {},
      orderId: 23,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
    {
      id: 7470,
      tenantId: "7416b42a-25cc-11e7-a500-00163e12f748",
      tableName: "product",
      isSystem: 0,
      fieldName: "field_wMA90VEc6PX44Q37",
      displayName: "计算公式",
      formType: "formula",
      defaultValue: null,
      isNull: 1,
      isSearch: 0,
      placeHolder: null,
      setting: {},
      orderId: 24,
      isDelete: 0,
      guideProfessions: [],
      isGuideData: false,
      isVisible: true,
      isHidden: 0,
      guideData: false,
    },
  ],
  productTypes: ["电器", "厨具", "空调"],
  productConfig: {
    productType: ["电器", "厨具", "空调"],
    productSearchOnMobile: true,
    serialNumberUnique: false,
    qrcodeEnabled: true,
    productTypeIsNull: false,
    fieldNameList: ["type", "name", "serialNumber"],
    hideDefaultLinkman: true,
  },
  id: "e72b907f-346d-11eb-a442-00163e304a25",
};

export default obj;
