//导出列选项
const allExport = [
  {
    exportAlias: "state",
    displayName: "工单状态",
  },
  {
    exportAlias: "createUser",
    displayName: "创建人",
  },
  {
    exportAlias: "allotUser",
    displayName: "派单人",
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "executorName",
    exportAlias: "executor",
    displayName: "负责人",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "executorTag",
    exportAlias: "executorTag",
    displayName: "负责人所属团队",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "synergies",
    exportAlias: "synergies",
    displayName: "协同人",
    formType: "user",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "createTime",
    exportAlias: "createTime",
    displayName: "创建时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "allotTime",
    exportAlias: "allotTime",
    displayName: "派单时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "acceptTime",
    exportAlias: "acceptTime",
    displayName: "接受时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "startTime",
    exportAlias: "startTime",
    displayName: "开始时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "completeTime",
    exportAlias: "completeTime",
    displayName: "完成时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "allotType",
    exportAlias: "allotType",
    displayName: "派单方式",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "acceptUsedTimeStr",
    displayName: "接单用时",
    exportAlias: "acceptUsedTime",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "taskUsedTimeStr",
    exportAlias: "taskUsedTime",
    displayName: "工单用时",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "workUsedTimeStr",
    exportAlias: "workUsedTime",
    displayName: "工作用时",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "taskResponseTimeStr",
    exportAlias: "taskResponseTime",
    displayName: "响应用时",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "onceOverTime",
    exportAlias: "onceOverTime",
    displayName: "曾超时",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "onceRefused",
    exportAlias: "onceRefused",
    displayName: "曾拒绝",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "oncePaused",
    exportAlias: "oncePaused",
    displayName: "曾暂停",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "onceRollback",
    exportAlias: "onceRollback",
    displayName: "曾回退",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "onceReallot",
    exportAlias: "onceReallot",
    displayName: "曾转派",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "oncePrinted",
    exportAlias: "oncePrinted",
    displayName: "曾打印",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "positionException",
    exportAlias: "positionException",
    displayName: "位置异常",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "inApprove",
    exportAlias: "inApprove",
    displayName: "审批状态",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 0,
    fieldName: "paymentMethod",
    exportAlias: "paymentMethod",
    displayName: "支付方式",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "reviewTime",
    exportAlias: "reviewTime",
    displayName: "回访时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "balanceTime",
    exportAlias: "balanceTime",
    displayName: "结算时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "closeTime",
    exportAlias: "closeTime",
    displayName: "关闭时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "updateTime",
    exportAlias: "updateTime",
    displayName: "最近更新",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "source",
    exportAlias: "source",
    displayName: "创建方式",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  }

  
]
// 选择列数据or表哥title
let fields = [
  {
    id: 476,
    tableName: "customer",
    isSystem: 1,
    fieldName: "taskNo",
    displayName: "工单编号",
    formType: "text",
    defaultValue: null,
    isNull: 0,
    isSearch: 1,
    placeHolder: null,
    setting: {
      customerNameDuplicate: false,
    },
    show: true,
    orderId: 0,
    isDelete: 0,
    guideProfessions: [],
    isGuideData: false,
    guideData: false,
  },
  {
    id: 476,
    tableName: "customer",
    isSystem: 1,
    fieldName: "templateName",
    displayName: "工单类型",
    formType: "text",
    defaultValue: null,
    isNull: 0,
    isSearch: 1,
    placeHolder: null,
    setting: {
      customerNameDuplicate: false,
    },
    orderId: 0,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "customer",
    displayName: "客户",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    show: true,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "tlmName",
    displayName: "联系人",
    exportAlias: "customerLinkman",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    show: true,
    guideProfessions: [],
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "tlmPhone",
    exportAlias: "customerPhone",
    displayName: "电话",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "taddress",
    exportAlias: "customerAddress",
    displayName: "客户地址",
    formType: "address",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "product",
    exportAlias: "product",
    displayName: "产品",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "level",
    displayName: "优先级",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "serviceType",
    displayName: "服务类型",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "serviceContent",
    displayName: "服务内容",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "planTime",
    displayName: "计划时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "description",
    displayName: "描述",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "createUserName",
    exportAlias: "createUser",
    displayName: "创建人",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "executorName",
    exportAlias: "executor",
    displayName: "负责人",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "synergies",
    displayName: "协同人",
    formType: "user",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "state",
    displayName: "工单状态",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 0,
    fieldName: "paymentMethod",
    displayName: "支付方式",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "createTime",
    displayName: "创建时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "allotTime",
    displayName: "派单时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "allotTypeStr",
    displayName: "派单方式",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "acceptTime",
    displayName: "接受时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "startTime",
    displayName: "开始时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "completeTime",
    displayName: "完成时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "acceptUsedTimeStr",
    displayName: "接单用时",
    exportAlias: "acceptUsedTime",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "taskUsedTimeStr",
    exportAlias: "taskUsedTime",
    displayName: "工单用时",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "workUsedTimeStr",
    exportAlias: "workUsedTime",
    displayName: "工作用时",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "taskResponseTimeStr",
    exportAlias: "taskResponseTime",
    displayName: "响应用时",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "onceOverTime",
    displayName: "曾超时",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "onceRefused",
    displayName: "曾拒绝",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "oncePaused",
    displayName: "曾暂停",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "onceRollback",
    displayName: "曾回退",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "onceReallot",
    displayName: "曾转派",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "oncePrinted",
    displayName: "曾打印",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "positionException",
    displayName: "位置异常",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "updateTime",
    displayName: "最近更新",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "reviewTime",
    displayName: "回访时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "balanceTime",
    displayName: "结算时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "closeTime",
    displayName: "关闭时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "source",
    displayName: "创建方式",
    formType: "user",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "eventNo",
    displayName: "关联事件",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
];


// 高级搜索数据
const advancedList = [
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "customer",
    displayName: "客户",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    show: true,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "tlmName",
    displayName: "联系人",
    exportAlias: "customerLinkman",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    show: true,
    guideProfessions: [],
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "area",
    exportAlias: "customerAddress",
    displayName: "区域",
    formType: "address",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "cusAddress",
    displayName: "详细地址",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "product",
    displayName: "产品",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "serviceType",
    displayName: "服务类型",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "serviceContent",
    displayName: "服务内容",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "paymentMethod",
    displayName: "支付方式",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {isMulti: false, dataSource:[
      '在线支付-支付宝',
      '支付宝收款码',
      '微信收款码',
      '银行卡收款',
      '其他支付-统一收款',
      '其他支付-月结',
      '其他支付-周结'
    ]},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "level",
    displayName: "优先级",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "tags",
    displayName: "选择团队",
    formType: 'select',
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    show: true,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "createUser",
    exportAlias: "createUser",
    displayName: "创建人",
    formType: "user",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "allotUser",
    exportAlias: "createUser",
    displayName: "派单人",
    formType: "user",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "executor",
    exportAlias: "createUser",
    displayName: "负责人",
    formType: "user",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "synergyId",
    displayName: "协同人",
    formType: "user",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "state",
    displayName: "工单状态",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {isMulti: false, dataSource:[
      '全部',
      '待指派',
      "已指派",
      '已接受',
      '进行中',
      '已完成',
      '已拒绝',
      '已结算',
      '已关闭',
      '已取消',
      '工单池',
      '未完成'
    ]},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "createTime",
    displayName: "创建时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "planTime",
    displayName: "计划时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "allotTime",
    displayName: "派单时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "acceptTime",
    displayName: "接受时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "startTime",
    displayName: "开始时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "completeTime",
    displayName: "完成时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "updateTime",
    displayName: "更新时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "reviewTime",
    displayName: "回访时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "balanceTime",
    displayName: "结算时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "closeTime",
    displayName: "关闭时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "allotTypeStr",
    displayName: "派单方式",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {isMulti: false, dataSource:[
      '全部',
      '手动派单',
      '工单池派单',
      '自动派单',
    ]},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "onceException",
    exportAlias: "createUser",
    displayName: "异常标记",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {isMulti: false, dataSource:[
      '曾超时',
      '曾拒绝',
      '曾暂停',
      '曾回退',
      '位置异常',
    ]},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "onceReallot",
    displayName: "曾转派",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {isMulti: false, dataSource:[
      '全部',
      '是',
    ]},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "oncePrinted",
    displayName: "曾打印",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {isMulti: false, dataSource:[
      '全部',
      '是',
      '否'
    ]},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "inApprove",
    displayName: "审批状态",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {isMulti: false, dataSource:[
      '全部',
      '审批中',
      '无审批'
    ]},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "source",
    displayName: "创建方式",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {isMulti: false, dataSource:[
      '全部',
      '导入创建',
      '手动创建',
      'API创建',
      '由事件创建',
    ]},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
];

//搜索显示字段
const Inquire = [
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "paymentMethod",
    displayName: "支付方式",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {isMulti: false, dataSource:[
      '在线支付-支付宝',
      '支付宝收款码',
      '微信收款码',
      '银行卡收款',
      '其他支付-统一收款',
      '其他支付-月结',
      '其他支付-周结'
    ]},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "tags",
    displayName: "选择团队",
    formType: 'select',
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    show: true,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "createUser",
    exportAlias: "createUser",
    displayName: "创建人",
    formType: "user",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "allotUser",
    exportAlias: "createUser",
    displayName: "派单人",
    formType: "user",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "executor",
    exportAlias: "createUser",
    displayName: "负责人",
    formType: "user",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "synergyId",
    displayName: "协同人",
    formType: "user",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "state",
    displayName: "工单状态",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {isMulti: false, dataSource:[
      '全部',
      '待指派',
      "已指派",
      '已接受',
      '进行中',
      '已完成',
      '已拒绝',
      '已结算',
      '已关闭',
      '已取消',
      '工单池',
      '未完成'
    ]},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "createTime",
    displayName: "创建时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "allotTime",
    displayName: "派单时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "acceptTime",
    displayName: "接受时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "startTime",
    displayName: "开始时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "completeTime",
    displayName: "完成时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "updateTime",
    displayName: "更新时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "reviewTime",
    displayName: "回访时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "balanceTime",
    displayName: "结算时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "closeTime",
    displayName: "关闭时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "allotTypeStr",
    displayName: "派单方式",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {isMulti: false, dataSource:[
      '全部',
      '手动派单',
      '工单池派单',
      '自动派单',
    ]},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "onceException",
    exportAlias: "createUser",
    displayName: "异常标记",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {isMulti: false, dataSource:[
      '曾超时',
      '曾拒绝',
      '曾暂停',
      '曾回退',
      '位置异常',
    ]},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "onceReallot",
    displayName: "曾转派",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {isMulti: false, dataSource:[
      '全部',
      '是',
    ]},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "oncePrinted",
    displayName: "曾打印",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {isMulti: false, dataSource:[
      '全部',
      '是',
      '否'
    ]},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "inApprove",
    displayName: "审批状态",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {isMulti: false, dataSource:[
      '全部',
      '审批中',
      '无审批'
    ]},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "source",
    displayName: "创建方式",
    formType: "select",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {isMulti: false, dataSource:[
      '全部',
      '导入创建',
      '手动创建',
      'API创建',
      '由事件创建',
    ]},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "eventNo",
    displayName: "关联事件",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 1,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
];
// 顶部筛选id
const selectIds = {
  createdId: "133d2ef7-19a8-11e7-8d4e-00163e304a25", //待指派
  allocatedId: "12fcb144-1ea3-11e7-8d4e-00163e304a25", //已指派
  acceptedId: "475e3328-1e63-11e7-8d4e-00163e304a25", //已接受
  processingId: "06db63fe-5017-11e7-a318-00163e304a25", //进行中
  exceptionId: "a78cbfec-d7d2-420f-9a56-32a503702f2d", //异常工单
  allId: "998620df-0d55-11e7-8d4e-00163e304a25", //全部工单
  unfinishedId: 'wangyue6-6666-6666-6666-666666666666', //未完成工单
  finished: '5ac722d9-1e63-11e7-8d4e-00163e304a25', //已完成工单 
};
module.exports = {
  fields,
  selectIds,
  advancedList,
  allExport,
  Inquire
};
