let fields = [
  {
    id: 476,
    tableName: "customer",
    isSystem: 1,
    fieldName: "taskNo",
    displayName: "工单编号",
    formType: "text",
    defaultValue: null,
    isNull: 0,
    isSearch: 1,
    placeHolder: null,
    setting: {
      customerNameDuplicate: false,
    },
    show: true,
    orderId: 0,
    isDelete: 0,
    guideProfessions: [],
    isGuideData: false,
    guideData: false,
  },
  {
    id: 476,
    tableName: "customer",
    isSystem: 1,
    fieldName: "templateName",
    displayName: "工单类型",
    formType: "text",
    defaultValue: null,
    isNull: 0,
    isSearch: 1,
    placeHolder: null,
    setting: {
      customerNameDuplicate: false,
    },
    orderId: 0,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "customer",
    displayName: "客户",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    show: true,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "tlmName",
    displayName: "联系人",
    exportAlias: "customerLinkman",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    show: true,
    guideProfessions: [],
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "tlmPhone",
    exportAlias: "customerPhone",
    displayName: "电话",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "taddress",
    exportAlias: "customerAddress",
    displayName: "客户地址",
    formType: "address",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "product",
    displayName: "产品",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "serviceType",
    displayName: "服务类型",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "serviceContent",
    displayName: "服务内容",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "planTime",
    displayName: "计划时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "description",
    displayName: "描述",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "createUserName",
    exportAlias: "createUser",
    displayName: "创建人",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "executorName",
    exportAlias: "executor",
    displayName: "负责人",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "synergies",
    displayName: "协同人",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "state",
    displayName: "工单状态",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "level",
    displayName: "优先级",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 0,
    fieldName: "paymentMethod",
    displayName: "支付方式",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "createTime",
    displayName: "创建时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "allotTime",
    displayName: "派单时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "allotTypeStr",
    displayName: "派单方式",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "acceptTime",
    displayName: "接受时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "startTime",
    displayName: "开始时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "completeTime",
    displayName: "完成时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "acceptUsedTimeStr",
    displayName: "接单用时",
    exportAlias: "acceptUsedTime",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "taskUsedTimeStr",
    exportAlias: "taskUsedTime",
    displayName: "工单用时",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "workUsedTimeStr",
    exportAlias: "workUsedTime",
    displayName: "工作用时",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "taskResponseTimeStr",
    exportAlias: "taskResponseTime",
    displayName: "响应用时",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "onceOverTime",
    displayName: "曾超时",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "onceRefused",
    displayName: "曾拒绝",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "oncePaused",
    displayName: "曾暂停",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "onceRollback",
    displayName: "曾回退",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "onceReallot",
    displayName: "曾转派",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "oncePrinted",
    displayName: "曾打印",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "positionException",
    displayName: "位置异常",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "updateTime",
    displayName: "最近更新",
    formType: "text",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "reviewTime",
    displayName: "回访时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "balanceTime",
    displayName: "结算时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
  {
    id: 5460,
    tableName: "customer",
    isSystem: 1,
    fieldName: "closeTime",
    displayName: "关闭时间",
    formType: "datetime",
    defaultValue: null,
    isNull: 1,
    isSearch: 0,
    placeHolder: null,
    setting: {},
    orderId: 1,
    isDelete: 0,
    guideProfessions: [],
    show: true,
    isGuideData: false,
    guideData: false,
  },
];

/* 顶部状态筛选数据 */
const filterList = [
  {
    id: 1,
    value: "待指派",
    num: 0,
  },
  {
    id: 2,
    value: "已指派",
    num: 0,
  },
  {
    id: 3,
    value: "已接受",
    num: 0,
  },
  {
    id: 4,
    value: "进行中",
    num: 0,
  },
  {
    id: 5,
    value: "异常工单",
    num: 0,
  },
  {
    id: 6,
    value: "全部工单",
    num: 0,
  },
];

module.exports = {
  fields,
  filterList,
};
